### ISSUE TITLE
Adding developer to sudoers fails when using 3.6.x version of OpenShift

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1011]
Looks like we have some code regression the way `minishift_kubeconfig` created and this make minishift failed during adding `developer` user to sudoers.

@jorgemoralespou 

```
$ ./minishift start --openshift-version v3.6.0-alpha.2
[...]
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.42.71:8443

You are logged in as:
    User:     developer

To login as administrator:
    oc login -u system:admin

Error during post cluster up configuration: Unable to add sudoer role
```

**Comment by jorgemoralespou** [comment]
So, here's what I saw, not sure what's the real problem, but taking a guess, would be because I have a real messed up kubeconfig in my HOME.

In the minishift_kubeconfig you save in .minishift/machines the user system:admin that's there is not a valid one. Probably could be taken from a previous run of minishift.

Think that every time you start minishift, in the $HOME/.kube/config you'll have an entry for the context (user, cluster and namespace). These will use the certificates from the minishift install you're creating. It might happen that the user you're finding has certificates from a previous run of minishift, hence not able to validate/login.

I would take 2 actions:
- First one, I would delete in $HOME/.kube/config everything related to minishift if I do "minishift delete" to prevent this from happening.
- Second, I would review the code to create minishift_kubeconfig as to get the correct information, or even use that context only for the minishift_install, so starting minishift with --config=.minishift/machines/minishift_kubeconfig and not messing with the one in $HOME. (This would avoid the first bullet).


How can you test if the minishift is properly created:
````
$ oc whoami --config=$HOME/.minishift/machines/minishift_kubeconfig
system:admin
````

If you don't get that user, the context is not correct.

You can check in regular context with:

````
$ oc login -u system:admin
$ oc whoami --config=$HOME/.kube/config
system:admin
````

Then you can compare the relevant entries from both files.

Hope this helps.

**Comment by praveenkumar** [comment]
@jorgemoralespou @csrwng So I tried to find out what actually causing the issue and looks like the way kubeconfig generated for v1.5.1 and v3.6.x is changed. For 3.6.x we only have `system:admin` cert for `127.0.0.1` not with the cluster IP. I generated kubeconfig for both version and pasted https://paste.fedoraproject.org/paste/ZmtA98~gc31O3MYo3cLpwQ. The way we were creating `minishift_kubeconfig` break because of it now. Any specific reason this changed?

**Comment by jorgemoralespou** [comment]
@praveenkumar not sure about what was the change in "oc cluster" that broke that, as there has been many changes related to how the node binds to an ip so that roaming of IPs work. As you recall, there's an issue in "oc cluster/minishift" where if you have a cluster and the host/VM changes it's IP, the cluster might not longer work. This might be a change coming for there.

@csrwng We need you to look into this, as this will break minishift moving forward.

**Comment by csrwng** [comment]
@praveenkumar (sorry for the delayed response) The config that is generated internally will only contain a server entry for 127.0.0.1 and not the external server IP. This was part of the change to support changing external ips: https://github.com/openshift/origin/pull/13112. However, the config that is generated for the client (at ${HOME}/.kube/config) is correct... it includes the external server name.

**Comment by hferentschik** [comment]
>  The config that is generated internally will only contain a server entry for 127.0.0.1 and not the external server IP. This was part of the change to support changing external ips: openshift/origin#13112. However, the config that is generated for the client (at ${HOME}/.kube/config) is correct... it includes the external server name.

So here we go, we look at the wrong config.

**Comment by hferentschik** [comment]
@praveenkumar or @budhrg - can any of you two take care of this? This is a quite important issue.

**Comment by budhrg** [comment]
@hferentschik it is assigned to @praveenkumar  and I believe he is working on it.

**Comment by praveenkumar** [comment]
@csrwng right so pastebin which I provided is what we get `~/.kube/config` for different version of openshift and what we have right now https://github.com/minishift/minishift/blob/master/pkg/minikube/kubeconfig/config.go#L62-L102 which take care of caching current context of config file to `~/.minishift/machine/minishift_kubeconfig`  because we can't directly copy complete `~/.kube/config` as it is which contain others context if I have more than one. 

Till now we were making decision to append User certs on based on `system:admin/<server_ip>:8443` which was working as expected but not any more because we do now have `system:admin/127-0-0-1:8443` and under that user cert are. 

There is easy fix/hack which is like https://github.com/minishift/minishift/pull/1028 but does it best approach provided we need to support 1.4/1.5 version also.

**Comment by hferentschik** [comment]
Merged via pull request #1028

**Comment by hferentschik** [comment]
I think we will have to re-open this issue or create a follow up issue. See discussion starting https://github.com/minishift/minishift/pull/1017#issuecomment-309434671 

The current approach won't work if one starts with 1.5.x, then provisions a 3.6.x and then back to 1.5.x.

**Comment by hferentschik** [comment]
On second thought, how come that on the host KUBECONFIG  I have something like 127.0.0.1 and how does this even work? And how would this ever work with multiple instances? 

@budhrg @praveenkumar Are we looking at the internal Kube config or the one on the host? Something is really fishy here.

**Comment by jorgemoralespou** [comment]
@hferentschik @praveenkumar I would think that kubeconfig should not be a general file for all the "profiles" but rather for the VM created, if you tackle #126, probably this would not be an issue anymore.

In any case, as #126 will probably require a lot of changes to keep config/files per profile/VM, I would consider that a top feature. As otherwise, you'll be working on many things probably twice. IMHO.

**Comment by hferentschik** [comment]
@csrwng, there might be a misunderstanding here. So you were saying:

> The config that is generated internally will only contain a server entry for 127.0.0.1 and not the external server IP. This was part of the change to support changing external ips: openshift/origin#13112. However, the config that is generated for the client (at ${HOME}/.kube/config) is correct... it includes the external server name.

So on the host ${HOME}/.kube/config should contain entries for the developer and system:admin using the external server name (or in our case the VM IP). However, what we are seeing is that the entry for system:admin ends up to be:

    system:admin/127-0-0-1:8443

That cannot be right, or?

**Comment by hferentschik** [comment]
Merged second related pull request #1041

**Comment by chmouel** [comment]
I am still getting this error with v1.5.0+ae62cf2 : 

![image](https://user-images.githubusercontent.com/98980/30110425-641c6d54-930a-11e7-9e85-db54b8e284c6.png)

**Comment by budhrg** [comment]
@chmouel , Could you try again by removing `$HOME/.kube/config` if you could remove kube/config file? This `kube/config` file store all the credentials so deleting it might loose credentials for other cluster you had created for minikube probably.

**Comment by chmouel** [comment]
@budhrg  Still the same thing, http://sprunge.us/RZTG (compiled from github master)

It seems that it has to do with the  localhost binding : 

    minishift start --public-hostname localhost --routing-suffix 127.0.0.1.nip.io --vm-driver=kvm --memory=6144 --cpus=4 --disk-size=50g

this works without the public-hostname routing-suffix switch

(should I open a new bug?)

**Comment by budhrg** [comment]
> (should I open a new bug?)

@chmouel , Please go ahead. At least if there is no implementation then we need documentation fix otherwise.

**Comment by GolanTrevize10** [comment]
Hi, I have the same problem with v1.9.0+a511b25 in Windows. These are my complete logs

$  minishift start --vm-driver=virtualbox
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Starting profile 'minishift'
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ...........................................-- Setting proxy information ... .OK
 OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
   http-proxy ... OK
   https-proxy ... OK
   no-proxy ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
Pulled 1/4 layers, 26% complete
Pulled 1/4 layers, 72% complete
Pulled 2/4 layers, 87% complete
Pulled 3/4 layers, 91% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
OpenShift server started.

The server is accessible via web console at:
    https://192.168.99.102:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

Error during post cluster up configuration: Unable to add sudoer role

I tried to delete the .kube/config file but still the same
