### ISSUE TITLE
Allow add-ons to define which version of `oc` should be installed

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#1044]
The `oc` binary is typically found on the users `$PATH` and could be quite old. It would be nice if we could supply a minimum `oc` version (e.g. 1.5/3.5) so that `minishift addons apply` could check and give some kind of warning like

```
WARNING: oc version: 1.3 is too old
the foo addon requires a minimum of version: 1.5

to download the new version please use:  https://github.com/openshift/origin/releases/latest/
```

**Comment by hferentschik** [comment]
The _oc_ version used by the add-on mechanism is the one cached by Minishift which aligns with the OpenShift version bootstrapped. The $PATH does not come into play here and the binary should never be out of date. One of the key features of current Minishift is that it caches the "right" version of _oc_ on your host. If you want to use it, run `minishift oc-env`. 

I am going to close this issue, since I don't think there is anything we need to do here.
