### ISSUE TITLE
minishift start fails at "Checking Docker client" while on VPN

### ISSUE THREAD

**Issue by jgreene-cwt** [minishift/minishift#1127]
Hello -
My dev team is coming up to speed on OpenShift Origin, and are able to successfully run the following minishift startup locally while connected to our domain at the office:

`minishift start --memory 4096 --cpus 2 --vm-driver virtualbox --show-libmachine-logs --iso-url centos`

So we have VirtualBox installed, and all works fine.  However, we are fortunate to be able to work remotely occasionally, running over VPN.  When we try to start minishift in this remote case while over VPN using the same start command, we get an error with the following in the logs when Docker is being checked:

```
Setting Docker configuration on the remote daemon...
-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     Please install Docker tools by following instructions at:

        https://docs.docker.com/windows/

     Once installed, run this command with the --create-machine argument to crea
te a
     new Docker machine that will run OpenShift.

   Caused By:
     Error: Get https://192.168.99.100:2376/_ping: dial tcp 192.168.99.100:2376:
 connectex: A connection attempt failed because the connected party did not prop
erly respond after a period of time, or established connection failed because co
nnected host has failed to respond.
OpenShift provisioning failed. origin container failed to start.
```

I've googled this issue, and although I see some similar issues, I'm not sure if there's actually an explanation or solution.  We work on Windows 7 boxes and are using VirtualBox 5.1.22.  

As a reminder, we have no problem running on our domain at the office, or running off VPN (in this case, sometimes, we have to recover by doing a minishift delete, followed by another minishift start, but it DOES start successfully after that).

We are hoping there's a viable solution for this problem so we can use minishift over VPN.  Any help with this would be appreciated

**Comment by gbraad** [comment]
One of the reasons of this can be that the communication between the `oc` client and the VM instance is not possible. This happens on Hyper-V for instance when an IPv6 address is assigned to the VM.
Although you are on Virtualbox, you are using a VPN, and therefore it sounds much like what we have addressed in the troubleshooting guide: https://github.com/minishift/minishift/blob/master/docs/source/using/troubleshooting.adoc#hyperv-fails-openvpn
It seems due to the configuration of your VPN software, you route too much over the outbound connection.

However I am confused about "use minishift over VPN". Can you explain more what you mean with this? As you are actually targeting your local system to run an OpenShift cluster.

Can you also explain more about the VPN solution you are using and how it is configured?

Note: we might have to adjust the troubleshooting guide to be more broadly defined and also cover macOS, or just inform: "When using a VPN, networking issues can occur".

**Comment by jgreene-cwt** [comment]
Thanks for such a quick reply.  Sorry about my choice of words ("minishift over VPN").  All I mean by this is that when we start up OpenShift locally using 'minishift start...', we get the error I described in my post whenever we connect our machines remotely to our domain over VPN at the beginning of the workday.  However, we have no issue whenever we are in the office (not on VPN).

Also, I had run across the hyper-v link you provided, and the workaround there was to disconnect from VPN, which is what we know about, but is of course not ideal for us.

As far as our VPN configuration goes, I'm not sure what I can provide (or am allowed to).  Is there something in particular you would suggest that I check?  Also, about your notion to update the troubleshooting guide to inform:  "When using a VPN, networking issues can occur"., does this imply that a solution/fix is probably out of your control?  Surely other development teams use openshift locally while connected to a VPN...?

**Comment by gbraad** [comment]
In short: this issue has nothing to do with OpenShift itself, but all about how the virtual Networking stack works for the hypervisor. This is complicated, as each hypervisor uses a different method, or even provides different solutions to handle it (like NAT, bridged,, host-only, etc). You would not be far from the conclusion when you said: "it is out of our control", as this is also related to  how the VPN software is configured to operate: selective routing, or route all traffic, etc....

To assist, I would like to know what is used: OpenVPN, F5, Dell SonicWall, Cisco, Pulse Secure... or different.

**Comment by jgreene-cwt** [comment]
Ok, our VPN solution is Netscaler Gateway - Citrix.  Thank you again for looking at this.

As an aside, I didn't necessarily think that OpenShift was the culprit here.  I was just hoping there was some optional configuration pertaining to something like IP assignment or the like that would take care of it.  But after googling for a while, I realized there probably wasn't going to be a quick solution around OpenShift.

**Comment by gbraad** [comment]
First, OpenShift curently is picky about being assigned the same IP address (#343 #593), so this is something that would already be a problem... as the VM would need to have a local IP address and an address on the VPN range? (I would not suggest the last, unless you really configure this yourself... for instance with a reverse-proxy).

NetScaler is not one of the VPN solutions I am familiar with, but perhaps it might also help to ask your local system administrator to assist. The problem stems from the fact that the VPN is solution is maybe too greedy to route all traffic. While actually, you should exclude the network range which is used for VMs, which in your case is: `192.168.99.1/24`.

**Comment by gbraad** [comment]
Docker machine, a framework we utilize, describes the situation as follows:

_A hang could be due to a variety of factors, but the most common suspect is networking. Consider the following:_
  * _Are you using a VPN? If so, try disconnecting and see if creation will succeed without the VPN. Some VPN software aggressively controls routes and you may need to manually add the route._

[ref](https://github.com/docker/machine#troubleshooting)

Closing this issue in favor of a documentation task for the time being. Will try to add some test for this as part of #485.

**Comment by malcolmm83** [comment]
I'm trying to run minishift on windows 10 and my VPN is Pulse Secure.  Any specific advice for me?  I found a workaround for Docker Toolbox using port mapping:

VBoxManage modifyvm "default" --natpf1 "default,tcp,,2376,,2376"
export DOCKER_HOST="tcp://localhost:2376"

This is very ugly.  I'm wondering if there's a way to apply a similar method for minishift?  I'm guessing there's more than just DOCKER_HOST and maybe more port numbers that would be required.
