### ISSUE TITLE
Behaviour of automatic installation of addons 

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1203]
I have tried to run coolstore.feature test, which failed to me. The problem is that between runs of integration tests, the integration-test folder is not being deleted. Due to this fact the addons folder is not being populated by default addons - aka automatic installation of default addons. 

Question is: **In which cases we want minishift to automatically install addons?**

Currently it is:

- minishift home folder does not exist
- minishift home folder is completely empty

Should it also trigger automatic installation when "addons" folder is not present in minishift home? Now it just creates empty folder called "addons".

**Comment by LalatenduMohanty** [comment]
I think add-ons should get installed during start command, refer https://github.com/minishift/minishift/pull/990. But it is not happening for me either.

**Comment by LalatenduMohanty** [comment]
So this seems to be a bug, as @agajdosi mentioned, we are seeing the issue
* If the addons directory is deleted manually by the user i.e. rm -rf ~./minishift/addons 
or 
* If the the directory .minishift is created by the user i.e. any manual intervention to addons directory structure breaks the default installs of addons.

**Comment by gbraad** [comment]
This depends on the expectation. First run would have to install... but why this is important, is the upgrade scenario. Does this work as expected? Does this populate the folder?

**Comment by LalatenduMohanty** [comment]
I think the `minishift start` should install add-ons if there is no addons directory in minishift_home. But when the addons directory is empty it should not install the addons during start. Because that mean user might have explicitly deleted the add-ons. 

Currently it is only installing the add-ons if minishift_home is present or if it is empty. Refer: https://github.com/minishift/minishift/blob/master/cmd/minishift/cmd/root.go#L86

**Comment by LalatenduMohanty** [comment]
Also does user need to delete the default add-ons or should we tell users how to do that i.e. adding to documentation.

**Comment by hferentschik** [comment]
> We should move this code to start.go as we check if it is a VM creation or we are just re-starting the VM.

I don't think there is a need for that. This is imo an unnecessary check. We check add-ons on fresh installs and on `minishift update`. After that it is up to the user. I don't really see an issue here. Also a user can re-install add-ons at any time `minishift add-ons install --default [--force]`. I am trying to see the problem here. 

The idea had always been to do the minimal and then leave it up to the user. 

> Also does user need to delete the default add-ons or should we tell users how to do that i.e. adding to documentation?

This is a different issues to add uninstall functionality. +1 to adding this. Whether we should document anything for now, I don't know. I think it is as easy to implement the un-install functionality.

**Comment by hferentschik** [comment]
Also, currently exciting checks of this form are in root.go in PersistentPrePrun - https://github.com/minishift/minishift/blob/2600c4f2a23e3fc63b370450257d3ab581e90f07/cmd/minishift/cmd/root.go#L113.

_start.go_ is the wrong place for this. Several commands arounds add-ons are executable and make sense without having to start the VM. If changing anything then root.go and the PersistentPreRun is the place to do it.

**Comment by LalatenduMohanty** [comment]
> Also a user can re-install add-ons at any time minishift add-ons install --default [--force]. I am trying to see the problem here.

personally I do not like this to do this. This should be implicitly taken care by Minishift. Specially when I developing stuff sometimes I need to delete the minishift_home and then create the minishift_home and then copy the cache directory and I expect Minishift to take care of the rest. 


> start.go is the wrong place for this. Several commands arounds add-ons are executable and make sense without having to start the VM. If changing anything then root.go and the PersistentPreRun is the place to do it.

Make sense. Agree to this.

**Comment by hferentschik** [comment]
> This should be implicitly taken care by Minishift. 

As long as it does not get in the way of users intention. I guess instead of checking for a non existing $MINISHIFT_HOME we check for an existing $MINISHIFT_HOME/add-ons. If it does not exist we create it and copy the default add-ons into it. This is pretty much harmless, since it does not enable anything. Does this cover your needs?

> Specially when I developing stuff sometimes I need to delete the minishift_home and then create the minishift_home and then copy the cache directory and I expect Minishift to take care of the rest.

I am not sure whether your needs as actual Minishift developer are a good measurement here. It is really the user of Minishift we need to keep in mind.

**Comment by LalatenduMohanty** [comment]
> I guess instead of checking for a non existing $MINISHIFT_HOME we check for an existing $MINISHIFT_HOME/add-ons. If it does not exist we create it and copy the default add-ons into it. This is pretty much harmless, since it does not enable anything. Does this cover your needs?

+1. This will be simple fix.

**Comment by hferentschik** [comment]
Merged via pull request #1265
