### ISSUE TITLE
Error in creating machine when trying to start minishift to use vitualbox as vm driver:

### ISSUE THREAD

**Issue by sanjar** [minishift/minishift#1214]
I am getting following error in creating machine when trying to start minishift to use vitualbox as vm driver:

```
C:\software\minishift-1.3.0-windows-amd64>minishift.exe start --vm-driver virtualbox
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0802 16:03:41.180440 22944 start.go:278] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storageattach minishift --storagectl SATA --port 0 --device 0 --type dvddrive --medium C:\Users\msaniar.APAC.minishift\machines\minishift\boot2docker.iso failed:
VBoxManage.exe: error: The medium 'C:\Users\msaniar.APAC.minishift\machines\minishift\boot2docker.iso' can't be used as the requested device type
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage.exe: error: Invalid UUID or filename "C:\Users\msaniar.APAC.minishift\machines\minishift\boot2docker.iso"
. Retrying.
```

  * Minishift version: v1.3.0+60ad6739
  * Virtualbox version: 5.1.26-117224
  * OS: Windows7 64 bits

**Comment by Ganitagya** [comment]
Please try to get the boot2docker.iso from [minishiftb2d iso](https://github.com/minishift/minishift-b2d-iso)

Get the path of the iso you just built and run the below command:
```minishift --alsologtostderr --show-libmachine-logs start --iso-url file://$PATHTOISO```

If it doesn't work then post the full logs

**Comment by gbraad** [comment]
It seems something is wrong with the boot2docker file. It is either incomplete, corrupted?... Can you try doing the following?

```
PS> minishift.exe start delete --clear-cache
PS> minishift.exe start --vm-driver virtualbox
```

**Comment by budhrg** [comment]
@sanjar , could you try as per @gbraad  comment ?

**Comment by sepphuber** [comment]
One note in addition to the above, because I haved searched for hours..:
If you use minishift on Windows with VirtualBox be sure that your current working directory is on the same driver letter than your home directory!
i.E.
Home directory:
C:\Users\myuser
Different working directory drive letter:
d:\
Leads to an error... 
Changing the drive to "c:" solved the problem
`
D:\>minishift start --vm-driver virtualbox                                                                        
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK                             
-- Checking the ISO URL ... OK                                                                                    
-- Starting profile 'minishift'                                                                                   
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...                                             
-- Minishift VM will be configured with ...                                                                       
   Memory:    2 GB                                                                                                
   vCPUs :    2                                                                                                   
   Disk size: 20 GB                                                                                               
                                                                                                                  
   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'    
 40.00 MiB / 40.00 MiB [=============================================================================] 100.00% 0s 
-- Starting Minishift VM ..... FAIL E1129 12:59:58.422833    1176 start.go:357] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/myuser/.minishift/cache/iso/b2d/v1.2.0/minishift-b2d.iso: Das System kann den angegebenen Pfad nicht finden.. Retrying.                     
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: open /Users/myuser/.minishift/cache/iso/b2d/v1.2.0/minishift-b2d.iso: Das System kann den angegebenen Pfad nicht finden.  
`
