### ISSUE TITLE
 mkdir() "/var/lib/nginx/proxy" failed (13: Permission denied)

### ISSUE THREAD

**Issue by kylearctiq** [minishift/minishift#124]
**After I run this based on instructions:**
oc run hello-minishift --image=gcr.io/google_containers/echoserver:1.4 --port=8080 --expose --service-overrides='{"apiVersion": "v1", "spec": {"type": "NodePort"}}'
service "hello-minishift" created
**I see the creating container fails - when I look at log I see:**
oc logs -f hello-minishift-1-xxorz
2016/10/18 17:46:35 [emerg] 1#1: mkdir() "/var/lib/nginx/proxy" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/lib/nginx/proxy" failed (13: Permission denied)

Kyles-iMac:~ kyle_bassett$ oc get pods
NAME                       READY     STATUS             RESTARTS   AGE
docker-registry-1-4w4j0    1/1       Running            0          3m
hello-minishift-1-deploy   1/1       Running            0          2m
hello-minishift-1-xxorz    0/1       CrashLoopBackOff   4          2m

**I do see the service and can hit the webui**

 oc get svc
NAME              CLUSTER-IP      EXTERNAL-IP   PORT(S)                 AGE
docker-registry   172.30.66.90    nodes         5000/TCP                10m
hello-minishift   172.30.195.99   nodes         8080/TCP                8m
kubernetes        172.30.0.1      <none>        443/TCP,53/UDP,53/TCP   10m

Can someone advise what the hello-minishift pod is for and if it is required?

Thanks
Kyle

**Comment by hferentschik** [comment]
Closing this issue as out of date.

**Comment by hferentschik** [comment]
It seems you used an out of date tutorial from the README. You could try the latest minishift release (1.0.0-beta.1) and follow the updated instructions.

**Comment by hangtwenty** [comment]
I keep getting this. Here's my info.

```
$ minishift version
Minishift version: 1.0.1

$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://192.168.64.2:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

$ oc run echoserver --image=gcr.io/google_containers/echoserver:1.5 --port=8080

deploymentconfig "echoserver" created

$ oc logs --follow echoserver-1-5frg2
2017/06/15 23:06:18 [emerg] 1#1: mkdir() "/var/lib/nginx/proxy" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/lib/nginx/proxy" failed (13: Permission denied)
```

**Comment by hangtwenty** [comment]
I have just moved onto running other examples but I am still curious what is wrong with this one. Does it basically come down to, this echoserver container doesn't do the right user/groups set up? ( https://blog.openshift.com/understanding-service-accounts-sccs/ )

**Comment by jorgemoralespou** [comment]
@hangtwenty probably that container requires to do an action that is not allowed. Could you paste the Dockerfile to that container, and I might be able to give you an answer.

**Comment by hferentschik** [comment]
> probably that container requires to do an action that is not allowed. Could you paste the Dockerfile to that container, and I might be able to give you an answer.

+1

**Comment by hangtwenty** [comment]
Page about this container is here, https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/echoserver (hitting gcr.io/google_containers/echoserver redirects me there). I don't have exact Dockerfile but here is the `docker history`

```
$ docker history --no-trunc gcr.io/google-containers/echoserver:1.5
IMAGE                                                                     CREATED             CREATED BY                                                                                                              SIZE                COMMENT
sha256:c598f57bb9384d51fcf14513426826590b74728146c498bb0cd549a043943063   12 days ago         /bin/sh -c #(nop) ADD file:3c20971b6163a65609831c0305d567a7e7fa04bcca05d5d204c672108dfe84fc in README.md                437 B
<missing>                                                                 12 days ago         /bin/sh -c #(nop) ADD file:cea00a614e73b063d1929986491fc010553b66efd9520ac6db037b679e807f14 in /etc/nginx/nginx.conf    3.04 kB
<missing>                                                                 4 weeks ago         /bin/sh -c #(nop)  CMD ["nginx" "-g" "daemon off;"]                                                                     0 B
<missing>                                                                 4 weeks ago         /bin/sh -c #(nop)  EXPOSE 443/tcp 80/tcp                                                                                0 B
<missing>                                                                 4 weeks ago         /bin/sh -c ln -sf /dev/stderr /var/log/nginx/error.log                                                                  11 B
<missing>                                                                 4 weeks ago         /bin/sh -c ln -sf /dev/stdout /var/log/nginx/access.log                                                                 11 B
<missing>                                                                 4 weeks ago         /bin/sh -c /tmp/build.sh                                                                                                51 MB
<missing>                                                                 4 weeks ago         /bin/sh -c #(nop) COPY file:7cde58db13fa7e26df491733ecbd75484176a0516bb8f1cc9171e4ba22819ce8 in /tmp                    8.67 kB
<missing>                                                                 4 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/bash"]                                                                                    0 B
<missing>                                                                 4 weeks ago         /bin/sh -c #(nop) ADD file:7bbdc7f081b1fbacfc5c0e7d30fa90d5b86794a8db3df43232d054e7f3080293 in /                        52.5 MB
```

**Comment by hangtwenty** [comment]
I think users are likely to try this container out because it is used in other tutorial material, for example:

* https://github.com/kubernetes/minikube#quickstart ([same steps show up in other tutorial locations like this one](https://stackoverflow.com/documentation/kubernetes/4099/getting-started-with-kubernetes/14274/installing-minikube#t=201706192317453953774) )

I know it is not minishift's responsibility to answer to minikube's instructions. **However,** I think it is perfectly natural for a beginner to cross these wires and see what they can/can't do with minishift, after coming from Kubernetes or minikube.

----

Hmm, maybe we could avoid people running this and getting confused, by offering a different example instead. Such as a Dockerfile or image (on DockerHub), that is basically `echoserver` idea or similar, but does the right `USER` setup to play nice with minishift. If people get that positive example to try out, they won't try the wrong thing.

I have to say as a beginner to OpenShift, this misunderstanding really gave me a jolt, and it's good that I was enthusiastic for OpenShift/minishift already; otherwise it would have made me feel like it was hard to approach.

**Comment by hferentschik** [comment]
>  by offering a different example instead

But Minishift does have a different example - https://docs.openshift.org/latest/minishift/getting-started/quickstart.html#deploy-sample-app

Or are you saying that Minikube should use an example which will also work on Minishift? 

> I have to say as a beginner to OpenShift, this misunderstanding really gave me a jolt, and it's good that I was enthusiastic for OpenShift/minishift already; otherwise it would have made me feel like it was hard to approach.

Thanks for the honest feedback. Much appreciated. Definitely understand your concern.

**Comment by jorgemoralespou** [comment]
@hferentschik that container is made to run as a specific user, hence it requires the anyuid.

@hangtwenty you can do:

````
oc add policy add-scc-to-user anyuid -z default --as=system:admin
oc rollout cancel dc/echoserver  # To cancel last deployment if still in progress
oc rollout latest dc/echoserver
````

An yes, agree that the error message is not very intuitive.

**Comment by hangtwenty** [comment]
@hferentschik Oh, I see, silly me. I think when I hit this two things happened.

* I saw the `new-app` command and for some reason I thought this was exercising the whole build pipeline feature of openshift, rather than "just" running or deploying a one-off. vague impression, but meant to circle back back
* Then I think I clicked "Interacting with OpenShift" link and went down a different path and forgot about trying the node.js new-app thing.

Now looking at help for `oc new-app` yeah it does include build etc ... and looking at README (https://github.com/openshift/nodejs-ex#build-the-app), it says

> `oc new-app` will kick off a build once all required dependencies are confirmed.

So I think even if I looked at that, I would have thought, hmm, no, I just want to run a container, and defied the instructions.

Does it make sense to give a beginner `oc new-app` right away? Could it make sense to encourage a `run` with less pieces? Then move them onto more interesting things, such as the existing example that uses `oc new-app`

**Comment by hangtwenty** [comment]
@jorgemoralespou Thanks for the tips about `anyuid`, I have a cursory understanding of SCC stuff ... but I see your tip aligns with  [this section of the docs](https://docs.openshift.org/latest/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile) and that helps me understand how to workaround this. This will be especially helpful as I relay some information to teammates.

**Comment by gbraad** [comment]
On Tue, Jun 20, 2017 at 7:21 AM, Michael Floering <notifications@github.com>
wrote:

> I think users are likely to try this container out because it is used in
> other tutorial material
>

Correct, this example app is actually one of the first I ran too. But it
also teaches you easily not to run root-user containers.
