### ISSUE TITLE
Getting 'API rate limit exceeded' while updating or starting minishift

### ISSUE THREAD

**Issue by tvieira** [minishift/minishift#1254]
Today I've got the message below few times:

`Error starting the cluster: Error attempting to download and cache oc: Cannot get the OpenShift release version v3.6.0: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.6.0: 403 API rate limit exceeded for 66.187.233.206. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 17m2.462768522s
`

This also happened when I tried to update Minishift through the command `minishift update`

I think it is worth mentioning in the development documentation that creating an API token and add the variable  `MINISHIFT_GITHUB_API_TOKEN ` helps not getting the rate limit message, at least this should work based on https://github.com/minishift/minishift/blob/e65bd066c9ee5012abbf0cf162e297967bd45342/pkg/util/github/github.go#L79

Unless this was already discussed and you reached to a conclusion, I can help with adding that to the documentation.

**Comment by hferentschik** [comment]
I am assuming that you are sitting in some sort of corporate networks where multiple people try to use Minishift and potentially update, right? Otherwise the rate limit should not be an issue, since we just do a few requests. However, if there are multiple users behind some internal network using Minishift, you get this issue, since GitHub only looks at the externally visible IP and limits the API access based on that. 

Either way, this has indeed be discussed and we said it would be good to add to the documentation. Maybe under the troubleshooting section. As you say, the easiest solution in this case is to set the API token. 

>  I can help with adding that to the documentation.

+1 That would be awesome. Much appreciated. We are looking forward to your pull request.

**Comment by hferentschik** [comment]
Merged via pull request #1257
