### ISSUE TITLE
Redeployment of an application takes more time

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1357]
When using CentOS ISO with minishift, redeploy an application takes a lot of time (around 10 minutes) and `event` logs shows following warnings/errors.  
Refer: https://issues.jboss.org/browse/CDK-166

```
E0906 18:56:30.970930    3220 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/94d1f756-9333-11e7-a3b3-52540022febb-deployer-token-63kch\" (\"94d1f756-9333-11e7-a3b3-52540022febb\")" failed. No retries permitted until 2017-09-06 18:57:02.970907748 +0000 UTC (durationBeforeRetry 32s). 
Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/94d1f756-9333-11e7-a3b3-52540022febb-deployer-token-63kch" (volume.spec.Name: "deployer-token-63kch") pod "94d1f756-9333-11e7-a3b3-52540022febb" (UID: "94d1f756-9333-11e7-a3b3-52540022febb") 
with: remove /var/lib/minishift/openshift.local.volumes/pods/94d1f756-9333-11e7-a3b3-52540022febb/volumes/kubernetes.io~secret/deployer-token-63kch: device or resource busy
```

This seems like a Kubernetes issue : https://github.com/kubernetes/kubernetes/issues/51835

**Comment by LalatenduMohanty** [comment]
The root cause of the issue is that Kubernetes tries to delete the POD and associated kubernetes.io~secret but  it can not delete it (hence the error `device or resource busy`). It only happens when `oc cluster up` access the config/data/volume directories through symbolic links.  
Here are the symbolic links which Minishift uses as we use the persistent storage partition. 

```
hostConfigDirectory  = "/var/lib/minishift/openshift.local.config"
hostDataDirectory    = "/var/lib/minishift/hostdata"
hostVolumesDirectory = "/var/lib/minishift/openshift.local.volumes"
hostPvDirectory      = "/var/lib/minishift/openshift.local.pv"
``` 
Workaround: 

Provide following flags to `minishift start` 
--host-config-dir /mnt/sda1/var/lib/minishift/openshift.local.config
--host-data-dir /mnt/sda1/var/lib/minishift/hostdata
--host-pv-dir /mnt/sda1/var/lib/minishift/openshift.local.pv
--host-volumes-dir /mnt/sda1/var/lib/minishift/openshift.local.volumes

**Comment by budhrg** [comment]
still to do

**Comment by praveenkumar** [comment]
Since it resolved downstream because of the new version of Openshift. I am closing this now.
