### ISSUE TITLE
minishift fails to start service-catalog

### ISSUE THREAD

**Issue by thomasmckay** [minishift/minishift#1405]
```
      minishift config set image-caching false
      MINISHIFT_ENABLE_EXPERIMENTAL=on minishift start --iso-url centos \
            --openshift-version v3.7.0-alpha.1 \
            --v 5 --show-libmachine-logs \
            --extra-clusterup-flags="--version=latest --service-catalog=true" \
            --insecure-registry 172.30.0.0/16 --insecure-registry minishift --insecure-registry 192.168.0.24:53170

-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Installing template service broker ... OK
-- Installing service catalog ... FAIL
   Error: failed to register broker with service catalog: timed out waiting for the condition
```
I admit I'm not sure if this is a minishift issue or it lies somewhere else but it presents itself when running minishift. A service-catalog dev looked at it and thought maybe it was the version of templates(?) included in minishift? I'll try to get them to comment here with their thoughts.

**Comment by dymurray** [comment]
When helping @thomasmckay debug it appeared the the errors in the controller-manager pod indicated it was still using kind: Broker as opposed to kind: servicebroker which is the new schema. I think this might be related to the fact that the service catalog template used to deploy the service catalog is in the 'oc' binary itself and does not reflect the latest upstream service catalog. If that's the case I'm not sure if there is a better solution minishift could implement so that it works and we can deploy a broker as well.

If I am off the mark on this please let me know. Perhaps this could be a bug with 'oc' itself.

**Comment by budhrg** [comment]
@thomasmckay , could you give `--memory 4GB/6GB`

**Comment by thomasmckay** [comment]
@budhrg same when using --memory 6GB
The issue is related to a term in the template changing from "Broker" to "ServiceBroker" when running latest openshift/origin. Since this is baked into 'oc' this error is due to the mismatch between the image and the cli.

Maybe this isn't a use case that minishift desires to support (choosing images and oc versions).

**Comment by gbraad** [comment]
It depends... we support a developer use-case, this could also mean to use a custom setup if needed, or even unprovisioned.

**Comment by gbraad** [comment]
Not sure what to do with this issue...

**Comment by thomasmckay** [comment]
Closing this since not really a minishift problem but due to mismatch between openshift/origin image and 'oc' command.
