### ISSUE TITLE
Checking if xhyve driver is installed ... FAIL

### ISSUE THREAD

**Issue by ryanj** [minishift/minishift#1426]
I've upgraded to the latest minishift release (minishift v1.6.0+7a71565 running on OSX 10.12.6), and am now hitting some errors when trying to initialize the environment:

```bash
$ minishift start
-- Checking if xhyve driver is installed ... FAIL
   See the 'Setting Up the Driver Plug-in' topic for more information
ryans-MacBook-Pro:~ ryanj$ minikube config view
```

minikube is working fine (using virtualbox), and minishift 1.0 had been working fine as well.  Seems like xhyve shouldn't be necessary when virtualbox is running.

**Comment by ryanj** [comment]
I was expecting `minishift` to default to `virtualbox` when active/available (just like `minikube` does).  Setting `--vm-driver=virtualbox` got around this issue.

**Comment by praveenkumar** [comment]
@ryanj This is because in Minishift we make default vm-driver as default platform hypervisor (like for windows it's HyperV, macOS it's xhyve and for Linux it is kvm). We have document also around it
https://docs.openshift.org/latest/minishift/getting-started/installing.html#install-prerequisites

If you agree on then please close this issue.
