### ISSUE TITLE
Runner.Run() could return also the error message

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#1501]
In package `pkg/util` the Runner.Run() func does return only exitCode of executed command, which then causes all other functions to be poor when reporting about errors. For example the oc.Run() - https://github.com/minishift/minishift/blob/master/pkg/minishift/oc/oc.go#L79, which just returns `Unable to add sudoer role`.

Would be nice if the errors were more talkative.

**Comment by hferentschik** [comment]
+1

**Comment by anjannath** [comment]
Hi @agajdosi sorry to bug you again about this, but its been a long time since we discussed about this, could you please have a look at this [commit](https://github.com/anjannath/minishift/commit/99bb985e0cca29efb31a0a9332e3eba893c9d9f3) when you have some free time and let me know if this is what you had in mind.

**Comment by agajdosi** [comment]
Hi @anjannath, my pleasure to take a look. Thanks for taking this issue. AFAIR the commit looks like what I meant, now the error message will be more useful. I like the fact you keep the "Adding sudoer role" + you add the actual error 👍 Useful for less and more experienced users.
Commenting more on the code now..

**Comment by anjannath** [comment]
resolved via #1787
