### ISSUE TITLE
Fix the CentOS CI script to not fail when the minibot URL is not reachable

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#1527]
Since, minibot is deployed in temporary servers till now which is causing the minibot service url inconsistent which in result make the build fail if url is inaccessible. Eg - https://ci.centos.org/job/minishift-release/74/console (v1.7.0 release build).

My suggestion is to remove the minibot notification from centos-ci and add again once we get the consistent place for minibot.

**Comment by budhrg** [comment]
@hferentschik WDYT about it?

**Comment by hferentschik** [comment]
What's about starting minibot from its old place again instead for now while we are looking for a more permanent home. I'd prefer, since this is not only about CentOS CI. 

Also, if the build fails due to the URL not being accessible, I see this as an issue with the script. Failing notification should not fail the build. So imo:

* Let's restart minibot from its original location 
* Fix the script to not fail when the notification URL is not reachable

**Comment by budhrg** [comment]
> Let's restart minibot from its original location

Sure :+1: 

> Fix the script to not fail when the notification URL is not reachable

I was also thinking same. Will update this issue title with this line
