### ISSUE TITLE
openshift list service seems to report only http URLs

### ISSUE THREAD

**Issue by jeffmaury** [minishift/minishift#1564]
I have defined a route to the registry but with a TLS option.
The web console reports https://docker-registry-default.192.168.99.100.nip.io/ 
but 
`minishift openshift service list` reports:
```
|-----------|-----------------|----------|------------------------------------------------------|--------|
| NAMESPACE |      NAME       | NODEPORT |                      ROUTE-URL                       | WEIGHT |
|-----------|-----------------|----------|------------------------------------------------------|--------|
| default   | kubernetes      |          |                                                      |        |
|           | router          |          |                                                      |        |
|           | docker-registry |          | http://docker-registry-default.192.168.99.100.nip.io |        |
|-----------|-----------------|----------|------------------------------------------------------|--------|
```

**Comment by anjannath** [comment]
Is this still relevent or it got solved? Anyways, I will try to reproduce this and report here.

**Comment by praveenkumar** [comment]
@anjannath I don't think we resolved this and this is still valid.

**Comment by anjannath** [comment]
This might be caused due to github's pagination.. 

https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by gbraad** [comment]
???

The issue here is about the service list...

On Friday, April 20, 2018, Anjan Nath <notifications@github.com> wrote:
> This might be caused due to github's pagination..
>
> https://developer.github.com/v3/guides/traversing-with-pagination/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/zQfqzjvhWmO3xEqCGbL4SAQQlCCxxnq74DNNxMh7-3dlZnqD9B5jo_GHo0tdEOfio1le3ZzJCr22FwWieLe5O8fPRn4NvY_bi-oC_JQcIgNQc2_bRD9G9hABLVIo2UxApQuQ_SNiJL90ZoVnfDvEgRGyRi7VTw=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZhPyAUWjcQKko-ZHKoW2Mv4eMTGRks5tqaU3gaJpZM4P4cYW.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by anjannath** [comment]
Yes. :) It was only printing http URLs, secured routes were also prefixed
with http. That's what #2237 fixes + the refactor

>
