### ISSUE TITLE
Web Console API path not changed to public domain setting

### ISSUE THREAD

**Issue by mickeoL** [minishift/minishift#1598]
My case would be, I would like to share my minishift instance to my intranet network.

It looks like there is no option to choose the network / IP, e.g. if you try to set the virtualbox network interface to "bridge", it would just fail

So I would like to setup port forwarding, e.g. http://blog.brianjohn.com/forwarding-ports-in-os-x-el-capitan.html

In this case I am able to access to the web console, e.g. redirect port of machine IP:PORT to 192.168.64.4:8443 (minishift)

But all the API, e.g. "https://192.168.64.4:8443/api/v1" are still using the internal IP, which of course it can not be accessed externally. 

Are there any way to make it work properly?

**Comment by gbraad** [comment]
The issue here is not one, first of all to allow someone else to access the machine on the network: #1287
Second, the IP address can not be changed after startup/restart #1508 #1515, etc. This certainly happens when you move from host-only to a bridged setup. However, I am trying to work on a solution that allows to assign an IP address to the VM before OpenShift starts: #1457 . I am closing this issues, as the use-cases are covered in the other issues. Please add relevant information to the other issues mentioned here.

**Comment by gbraad** [comment]
Dup of #1287
