### ISSUE TITLE
Remove vmware-fusion mention/support from documentation

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#1602]
We should remove VMware-fusion from the host folder documentation since we are not even testing minishift against VMware-fusion and it is confusing for users who refer it and then try out.

**Comment by hferentschik** [comment]
+1

**Comment by athos-ribeiro** [comment]
Should it be removed just from the host folder documentation or from the whole documentation?

**Comment by gbraad** [comment]
Actually, from the whole document. It is not something we can test for as a
target.
At least the reference for the host folders has caused issues of false
expectation before.

**Comment by gbraad** [comment]
![untitled 4](https://user-images.githubusercontent.com/1894/32260342-3f82dc52-bf02-11e7-9220-3d528c756543.jpg)

From the landing page we claim to support VMwarr Fusion. I believe this should be reconsidered in light of effort to make this work (testing, development). /cc: @LalatenduMohanty @praveenkumar @agajdosi

**Comment by agajdosi** [comment]
@gbraad As most of automated tests happen in downstream, we mirror the CDK's requirements, where Win/VB, Win/HyperV, macOS/xhyve, macOS/VB, RHELserver/KVM and RHELworkstation/KVM has been requested.

There should not be a problem with running integration tests as they are with VMware, at least we could try it and see. Once we find it to work or we fix it, the community could start using it if there is a will for it.

I would like to see it automated, but for now I am not sure if we have any options to make it in upstream. For manual starts of integration tests, we can try to to run tests once a sprint I think.

**Comment by gbraad** [comment]
this is the point, it seems VMware Fusion (macOS) is not one of the CDK requirements... or is it? (Note: we do not even talk about VMware Workstation for Windows or Linux).

**Comment by agajdosi** [comment]
@gbraad I can't recall if there is any official document. But AFAIR I have never been asked to test it (same it is for VB on RHELs). When I have started oc CDK 2.x, we had the platforms we have now except later there was a discussion about adding RHEL workstation, so RHEL workstation is one extra platform which has been added.

**Comment by gbraad** [comment]
This needs clarification.

However, minikube has been in discussions to deprecate the vmwarfusion driver anyways, and the workstation driver hasn't seen a lot of development/maintenance. They are in the process of including an updated driver: https://github.com/kubernetes/minikube/pull/2118#issue-268519951

**Comment by gbraad** [comment]
I am for removing the code, but in the sense of a deprecation period. We already kinda mention we do not support the setup when they report an issue involving VMware. At the Minikube side there is:

   * kubernetes/minikube#2058 to drop support

Unless a maintained driver is available the current support is nothing more than flaky. The driver hasn't seen much development. The VMware repo of libmachine has not seen improvements for 2 years on their master: https://github.com/vmware/docker-machine/tree/master/drivers/vmwarefusion. The same for the official repo of libmachine https://github.com/docker/machine/tree/master/drivers/vmwarefusion which has only seen typo changes. Either the code is super-stable... or no-one provides support. The same for the minikube repo: https://github.com/kubernetes/minikube/tree/master/vendor/github.com/docker/machine/drivers/vmwarefusion they synced a year ago and have since not provide any fixes.

There is ongoing work

   * kubernetes/minikube#2118

which is a vmware fusion and workstation driver, but this will not be a drop-in driver for us, as there is likely no RPC support, which we would still need (as we use libmachine unmodified, while minikube has an in-repo modification).

**Comment by gbraad** [comment]
@minishift/minishift-dev Also important to note is that libmachine has no intention to add more functionality: https://github.com/docker/machine/pull/4280#issuecomment-338842944 such as an updated driver.

**Comment by budhrg** [comment]
> I am for removing the code, but in the sense of a deprecation period. We already kinda mention we do not support the setup when they report an issue involving VMware.

+1

**Comment by LalatenduMohanty** [comment]
Resolved by #1643
