### ISSUE TITLE
Allow driver options to be part of instance/profile configuration, eg. `hyperv-virtual-switch`

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1622]
In light of using profiles, we have to reconsider the environment variables used for setting the virtual switch. When you create an instance, you might want to assign it to another VSwitch, and with a specific `--network-ipaddress` and `--network-gateway`.

Network settings are in my opinion instance specific... environment variables are global and therefore always act as an override. To me personally they are more in the way than a help.

Fix #590 is in my opinion preferred. Solution #739 was chosen on the basis that #305 would take 'some' time => actually, the switch option should have been added here:

https://github.com/minishift/minishift/pull/773/files#diff-221fdad1b39f75fb2d0214c25944dcb3R421

as part of #773.

Take note that Minikube does the following:

https://github.com/kubernetes/minikube/blob/a34e91d54cf45039ba73cfce63168110f3e50b66/pkg/minikube/cluster/cluster_windows.go#L37
https://github.com/kubernetes/minikube/blob/33584026c1bbe92310c66926abfe3afe39381dd7/cmd/minikube/cmd/start.go#L59

which makes it part of the config options.

Note: using `_windows.go` specific implementation files or `GOOS == "windows"`, it can be prevented to flood the start command.

**Comment by gbraad** [comment]
For instance, I have one instance created on the DockerNAT network to talk to a registry mirror (configed with ipaddress) and another is on bridged/external vswitc). This is now jumbling with env to make this happen on recreate

**Comment by praveenkumar** [comment]
We implemented a generic solution for all the drivers when resolved https://github.com/minishift/minishift/issues/590 but that time we didn't have profiles + all docker-machine drivers were in support and it worked well. Now there are 2 different things happen.

1. xhyve and kvm driver has now not maintained anymore and minikube folks already started to put and depreciated message on the codebase (check https://github.com/kubernetes/minikube/pull/2227) So we also need to move accordingly and to do that we do need to consume the drivers which those folks are maintaining and developing (hyperkit and kvm2). Those drivers code are part of minikube repo and they create the binary and upload storage.google same way they do for minikube-iso. According to their driver implementation they don't have `mcnflag` which we currently use for driver options https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/driver_options.go#L36 

2. Profiles: since as a user I can have different value to for my hypervisors options (like network_bridge, ssh_user ..etc.) but right now since we handle it using environment variable which does not profile specific but a generic one and also not able to set those as part of `m config set`

I think we need to revisit it sooner than later and make sure we incorporate with minikube way of communicating with drivers.

@minishift/minishift-dev your view/suggestions please.

**Comment by budhrg** [comment]
> We implemented a generic solution for all the drivers when resolved #590 but that time we didn't have profiles + all docker-machine drivers were in support and it worked well.

Yes, during that time, it was the best solution but with profile introduction we need to think as we can't set two different hyperv for different profiles.

> xhyve and kvm driver has now not maintained anymore and minikube folks already started to put and depreciated message on the codebase (check kubernetes/minikube#2227) So we also need to move accordingly and to do that we do need to consume the drivers which those folks are maintaining and developing (hyperkit and kvm2).

 +1 Sure, in the long run, it is the best possible way.

> Those drivers code are part of minikube repo and they create the binary and upload storage.google same way they do for minikube-iso. 

So going to be more dependent on minikube code base after `minikube-iso` if minikube folks don't separate this code.

**Comment by hferentschik** [comment]
> So we also need to move accordingly and to do that we do need to consume the drivers which those folks are maintaining and developing (hyperkit and kvm2)

+1 to moving to hyperkit and kvm2. Where is the code exactly? You say they upload binaries? Do they have dedicated repos for these drivers or do they build all from the same source tree? 

I think it is also important that we get into a mode where we can handle the driver setup for the user. It should be a one-stop solution. Provided we consume the drivers as binaries, they should be downloaded and added to the cache. If we need root privileges for that at some point the user should be prompted for that. The alternative is to somehow have the driver code inlined, but at least with xhyve that would not work. 

From a usability point of view, I would make it a high priority to handle any required driver installation and configuration for the user. During the workshops, I recently gave this was one common sore points for attendees. 

Regarding exposing more options, like 'hyperv-virtual-switch'. If needed sure, however, I think it would be even more important to get into a state where this option is not even needed for a given default case.

**Comment by gbraad** [comment]
> Where is the code exactly? 

https://github.com/kubernetes/minikube/tree/master/pkg/drivers

**Comment by gbraad** [comment]
Slight off-topic, but @anfernee has proposed a driver for Minikube, after being denied to add new fucntionality to libmachine. I would appreciate if this can be a separate binary too... and work on installing this automatically, as this allows re-use for both projects. I am sure @r2d4 @dlorenc will appreciate this, as this will make maintenance a shared effort.

**Comment by praveenkumar** [comment]
As per f2f discussion, we agreed on to modify existing WIP PR and only change the codebase without adding any new functionality (like hyperv-virtual-switch) or adding any new driver (like kvm2). With this issue we just cleaning move from mflag stuff to machine config and in future we should add command line argument for driver specific requirement (like hyperv-virtual-switch ...etc.)
