### ISSUE TITLE
Run minishift without Internet connection

### ISSUE THREAD

**Issue by delubi** [minishift/minishift#1637]
I'm building minishift on a VM that has no Internet connection. When I tried to start minishift it failed as below. Looks like it's trying to connect to minishift.io and github and failed because my VM has no connectivity to Internet.

Is there a way to run minishift without Internet connection?

[root@ontazupocav0003 ~]# minishift start --iso-url=file:///root/minishift-b2d.iso
-- Checking if KVM driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ...
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present and active ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .............................. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
Error starting the cluster: Error attempting to download and cache oc: Cannot get the OpenShift release version v3.6.0: Get https://api.github.com/repos/openshift/origin/releases/tags/v3.6.0: dial tcp: lookup api.github.com on 10.69.0.153:53: dial udp 10.69.0.153:53: i/o timeout
[root@ontazupocav0003 ~]#

Thanks,
Forrest

**Comment by LalatenduMohanty** [comment]
@delubi It is not possible to do a fresh start of Minishift without Internet. However we have https://github.com/minishift/minishift/issues/397 in our roadmap. 

I am closing this issue as we can not go for complete offline use case with the current code base.

**Comment by gbraad** [comment]
Several things can help at the moment:

  * run a registry mirror on a local docker
  * use image caching

**Comment by delubi** [comment]
@gbraad : can you please elaborate how it can be done? Do I need both (local registry and image caching)?

Is there a list of images that I should pull from github and put in local registry to kick start the minishift?

Thanks,
Forrest

**Comment by gbraad** [comment]
These topics are described in our documentation and/or the Docker documentation and described in issues (on PTO ATM)

Image Caching is a way to cache the images and transfer them to another host (or for a restart/redeploy) so that the container images are copied to the VM before the OC deployment starts.

with a registry mirror, the images that are pulled will be stored in a local registry (that mirrors). this means that any consecutive deployment will of these images will be performed by touching the mirror first.

Note: both need you to have an active internet connection at least once during the process, either from the host or another.

**Comment by delubi** [comment]
@LalatenduMohanty : In my use case, I have another VM that can connect to Internet. Would the following work in theory?

1. On VM A that has Internet connection, build and start minishift.
2. Tar necessary files on VM A and transfer to VM B.
3. On VM B that doesn't have Internet connection, untar.
4. Start minishift on VM B.

Thanks,
Forrest

**Comment by gbraad** [comment]
Can you take the VM out of the situation and instead, tar the VM image itself (by making it on the host/settings that makes VM A connect), and then untar on the machine that would host VM B.

Or, do you have proxy connectivity?

**Comment by delubi** [comment]
@gbraad Taking the whole VM is not feasible in my case. I run VM A on my laptop via VMware player and run VM B on VMWare vCenter. Not able to export the whole VM from VMware player into an OVA and import in vCenter. Individual files transfer is probably the only way to share between the two VMs.

http/https proxy is not available.

**Comment by gbraad** [comment]
individual file transfers are not supported as the configuration of OpenShift is bound to an IP (certificates).

Note: Also, we do not test/support nested virtualization for VMware-based platforms. We only do this for KVM?Libvirt as this is part of our CI/Integration testing.

**Comment by gbraad** [comment]
Update: setting up a registry mirror could be done with https://gist.github.com/gbraad/7cb36210bd5effdeb788c34d6b433ac8 However, since we now have the `--no-provision` option, you can actually use a local Minishift instance to do this... or just use a vagrant/Virtual machine running CentOS to do the same, as you only have to rely on Docker to be available. Make sure the VMs are on the same virtual network.

```
$ docker run -d --restart=always -p 5000:5000 --name registry-mirror registry:2 
$ docker exec -it registry-mirror vi /etc/docker/registry/config.yml
```
and add the entries: 
```
proxy:
   remoteurl: https://registry-1.docker.io
   username: [your username]
   password: [your password]
```
and then restart this named container with:
```
$ docker restart registry-mirror
```

For Minishift configure a registry mirror:
```
C:\>minishift config set check-network-ping-host 10.0.75.1
C:\>minishift config set check-network-http-host http://10.0.75.1:5000/v2/
C:\>minishift config set insecure-registry 10.0.75.1
C:\>minishift config set registry-mirror http://10.0.75.1:5000
```
Note: use the IP address of the registry-mirror VM
