### ISSUE TITLE
Revisit the NodePort documentation

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1659]
Followup issue for https://github.com/minishift/minishift/issues/1651. 

We need to revisit https://docs.openshift.org/latest/minishift/openshift/exposing-services.html#nodeport-services  and see if it needs any modification as per the outcome of https://github.com/openshift/origin/issues/17165

**Comment by praveenkumar** [comment]
@LalatenduMohanty @gbraad looks like this is not fixed from openshift doc side yet https://github.com/openshift/openshift-docs/issues/6142 but what stopping us to use https://docs.openshift.org/latest/dev_guide/expose_service/expose_internal_ip_nodeport.html ?

**Comment by anjannath** [comment]
actually @LalatenduMohanty already mentioned about this link in the original issue [issue#1651/comment](https://github.com/minishift/minishift/issues/1651#issuecomment-341735170). I think we can use this link since the issue on openshift side is still not resolved and we are talking about exposng service via NodePort.

**Comment by gbraad** [comment]
Merged as 4d01da5b
