### ISSUE TITLE
Ability to delete more than one profile at once

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#1704]
$ minishift profile delete bar foo
     You have provided more arguments than required. You must provide a single profile name.

In the context of deletion of profiles, there is no need to limit to a single profile name. If you have mutliple profiles and want to clean out, it would be nice to do it in one go.

**Comment by praveenkumar** [comment]
Another thing which we need to consider here if a user provides non-exist profile along with exists profile then should we stopped there after or carry on with printing message about profile doesn't exist?

```
$ minishift profile delete foo bar test  # I only have foo, test 
profile `foo` is deleted successfully
profile `bar` doesn't exist      => should we stop the process or continue 
profile `test` is deleted successfully 
```

**Comment by anjannath** [comment]
This is still relevant, reopening.

**Comment by praveenkumar** [comment]
I don't see any problem to closing this because of it was created when profile feature was new and everyone wanted to try something with it now situation is different and folks know what they want to use plus we now only create profile with only some command not every other like we used to do before.

**Comment by budhrg** [comment]
Hence closing :)
