### ISSUE TITLE
OC fails to propagate start-build environment variable

### ISSUE THREAD

**Issue by bmsantos** [minishift/minishift#176]
Not sure if this is a ticket for minishift, but here goes:

```gherkin
Feature: OC start-build
Scenario: Should propagate environment variable to docker build
  Given a Dockerfile with an environment variable
  When the OC start-build is executed with --env
  Then the docker build will receive and substitute the environment variable with the new value
```

Dockerfile:
```dockerfile
ENV VERSION 0
```

Example OC command:
```bash
oc start-build --from-dir=. --follow --env VERSION=1 app-name
```

**Comment by hferentschik** [comment]
So, if I understand you correctly,  `--env VERSION=1` is not passed to the build container, correct? Or do you expect some variable substitution in the Dockerfiler? If so how does the Dockerfile look like? In the latter case I am not sure whether you have a wrong assumption. Either way, this issue seems to belong to https://github.com/openshift/origin

**Comment by bmsantos** [comment]
@hferentschik. It was the second case you've mentioned. I was expecting --env to be able to set the Dockerfile ENV or ARG values. I realize now that I might have misunderstood the command. What --env does is to set the environment variables for the container.
