### ISSUE TITLE
Document how persistent config options and env variables can be used

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#178]
The underlying config system used in MiniShift (Viper), has a hierarchical way of specifying options. They don't need to come only from the command line, but also from the environment or persistent config files. How to do this needs to be documented in the Minishift docs.

**Comment by LalatenduMohanty** [comment]
+1 I think it is a good idea to document it.

**Comment by hferentschik** [comment]
Config options are set via:

    minishift config set <key> <value>

ATM, there are only a couple supported. See https://github.com/minishift/minishift/blob/master/pkg/minikube/config/config.go

Regarding environment variables. Command flags can be specified bu using the flag name, uppercase it, replace - with _ and prefix MINISHIFT, eg MINISHIFT_SHOW_LIBMACHINE_LOGS.

We need a few tests around this, but this is the bottom line. See also https://github.com/spf13/viper

**Comment by hferentschik** [comment]
There is also something around environment variables as well - https://github.com/minishift/minishift/blob/master/docs/using.md#environment-variables

**Comment by hferentschik** [comment]
@thatdocslady @Preeticp - you guys want to review this. The first cut of the docs are in - https://github.com/minishift/minishift/blob/master/docs/using.md#persistent-configuration

One thing which I find misleading is actually in https://github.com/minishift/minishift/blob/master/docs/minishift_config.md:

> Configurable properties (enter as SUBCOMMAND): 
> ...

This does not make much sense to me. This somehow seems to imply to me that the properties are SUBCOMMANDS!? I think that needs better wording. Mind you, this is generated docs. To change this you will need to update the corresponding command file.

**Comment by gbraad** [comment]
Related to 'using.md'; shouldn't commands follow markup as code (using backticks) and add the link separate as a reference. WDYT?

**Comment by Preeticp** [comment]
You are right @gbraad, so, minishift start, stop, delete, config etc need to be within backticks with respective hyperlinks, missed that one.

**Comment by Preeticp** [comment]
I have the following suggestions, all have been clubbed together since I don't see an option to give line wise suggestion:
1. Consider replacing 'Using persistent configuration allows you to control Minishift's behavior without specifying actual command line flags, similar as using environment variables.' with 
'You can use persistent configuration to control Minishift's behavior without specifying actual command line flags, just as you use environment variables.'

2. Note that the following precedence order applies. > Note that to control the behaviour of Minishift the following precedence order is applied: 
3. A blank line before this sentence to separate this paragraph would be nice.

4. 'Each item in the list beloew takes precedence over the item below it:'> 'Each item in the following list takes precedence over the item below it:'

5. Based on this issue description these seem to be in hierarchical order, also if these need to be done in serial order, numbered list would be better, if not bullets are fine. 

6. Should the list read like this: 

- Flag as specified via the command line
- Set environment variables as described in the environment variables section
- Use persistent configuration option as described in this section
- Set default value as defined by Minishift

**Comment by hferentschik** [comment]
@Preeticp, do you want to take this and provide a pull request? We can take it from there.

**Comment by Preeticp** [comment]
Sure Hardy.

**Comment by hferentschik** [comment]
Merged via pull request #425
