### ISSUE TITLE
Run integration tests with image caching enabled

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#1799]
To achieve #1798, we need to run integration tests with image caching enabled

**Comment by hferentschik** [comment]
There are several considerations here. The problem with enabling image caching per default is that on the first start, if the core OpenShift images are not cached, a background thread is started to export these images. Without any additional hooks in integration tests, we would not have a way to fully control the state of the tests. A given feature might close the Minsihift instance before the export is complete. In this case the background process will eventually die as well, but for subsequent tests, there is no guaranteed behaviour in case you want to make any assertions based on the import/availability of these images. The export might have been aborted or it might have completed. 

At the very least we need a way to monitor the background process and wait for it to complete. ATM the process pid is reported at the end of the 'minishift start'. The problem is that one would need to extract the pid some way and use it for some _monitorPid_ step. Once we would have the pid the monitoring is easy, the problem is as said the extraction of the pid. One way could be to create a custom Minishift start step, replacing all steps of the form "executing "minishift start" succeeds". Under the hood we can then create the full life cycle of the Minsihfit VM and keep track of state, etc.

The alternative is something more generic: 

```Cucumber
     When executing "minishift start" succeeds
       And  image export completes    
     Then  openshift/origin-haproxy-router:v3.6.0 is cached
       And openshift/origin-docker-registry:v3.6.0 is cached
       And openshift/origin:v3.6.0 is cached
```

Under the hood we would look in the implementation of "image export completes" for the output of the previous command (the start command) and parse it for the pid. If it exists we start monitoring the pid until the process ends or the job times out. 

The question is how we put this into action. How does "image export complete" behave in the case there is no export due to the fact that the images are already cached? Ignore or fail? We could check the cache in the case there is no pid in the output from the start command. If there are core images which are not cached yet, then we also know we have an error.

Making sense :-) ? @agajdosi @amitkrout

**Comment by amitkrout** [comment]
> When executing "minishift start" succeeds
      And  image export completes    
     Then  openshift/origin-haproxy-router:v3.6.0 is cached
      And openshift/origin-docker-registry:v3.6.0 is cached
      And openshift/origin:v3.6.0 is cached

Looks good to me

> The question is how we put this into action. 

This really needs a spike to get a proper logic implementation imo. I would suggest lets have a high level logical structure and feedback of course.

**Comment by budhrg** [comment]
WDYT about above suggestions @agajdosi ?

**Comment by agajdosi** [comment]
@budhrg Suggested scenario seems fine to me. Not sure however about the implementation, maybe @amitkrout took a look on it. I can investigate next week if needed.

**Comment by amitkrout** [comment]
@budhrg From the latest commit i can see only the file name is changed (prepended by sequence of numeric starting from 1.). Godog will pick the sequence begin with 1. , 2. so on... and execute. Would you please add some content here to justify your logic

**Comment by budhrg** [comment]
@amitkrout @agajdosi , I was talking about Hardy's suggestion. Does it looks promising?

**Comment by agajdosi** [comment]
@budhrg I was also, as said, seems good to me, we need the step which will assure that the images were imported, most likely by checking the import process.

**Comment by budhrg** [comment]
As per discussion with @hferentschik, we are going to following solution 
- Test the caching behavior in single feature file and monitor the pid as describe in this comment https://github.com/minishift/minishift/issues/1799#issuecomment-349320277.
- Disable the caching in other feature files

@agajdosi Is there any way we can run `minishiift config set image-caching false` for all feature files except one feature? 
I understand we have RUN_BEFORE_FEATURE but then it will run that command before each feature files.
@agajdosi  can we introduce here to add exception to above case or the former solution of disabling caching in other feature files make sense?
