### ISSUE TITLE
Irregularities in commit message validation

### ISSUE THREAD

**Issue by robin-owen** [minishift/minishift#1804]
The commit message validation regular expression currently allows commit messages such as `cut v1x2y3` -- this is not as intended.

This is caused by the regular expression matching `.` to any character. These should be escaped in the regular expression as `\.` to explicitly match a period.

**Comment by robin-owen** [comment]
Note: the recent addition of `$$` to the end of the regular expression may also cause inadvertent failures, as this matches `EOLEOL` rather than a single end of line.

**Comment by gbraad** [comment]
I added a testcase: https://regex101.com/r/Iv69Jr/3

![image](https://user-images.githubusercontent.com/1894/33639538-b0f16fbe-da66-11e7-9d0b-00081c9e57bd.png)

Fixed with:
`^(Issue #[0-9]+ .*|cut v[0-9]+\.[0-9]+\.[0-9]+$)`

![image](https://user-images.githubusercontent.com/1894/33639562-e0693010-da66-11e7-974c-b96584547a37.png)

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1813
