### ISSUE TITLE
Unable to write to mountPath with PVC

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#1811]
### General information

  * Minishift version: v1.9.0+a511b25
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. https://gist.github.com/kameshsampath/916ef263f755656ace65d5315b3cb83c
  2. oc apply -f  https://gist.github.com/kameshsampath/916ef263f755656ace65d5315b3cb83c

### Expected
Keycloak pods should start successfully

### Actual
Keycloak pods does not start with  failure messages showing the unable to write to the folder which is mounted using PVC 

If you do a oc debug you will see the folder is mounted as `root` with others group not having write permissions to it.

Bit of debugging on the minishift vm showed that the following 
```
docker@redhat-msa-3-workshop:~$ sudo ls -ll /var/lib/minishift/openshift.local.pv
total 404
drwxrwx---    2 root     root          4096 Dec  6 14:18 pv0001
drwxrwx---    2 root     root          4096 Dec  6 14:18 pv0002
drwxrwx---    2 root     root          4096 Dec  6 14:18 pv0003
drwxrwx---    2 root     root          4096 Dec  6 14:18 pv0004
drwxrwx---    2 root     root          4096 Dec  6 14:18 pv0005
...
```

```
docker@redhat-msa-3-workshop:~$ sudo ls -ll /var/lib/minishift
total 16
drwxr-xr-x    3 root     root          4096 Dec  7 07:10 hostdata
drwxr-xr-x    4 root     root          4096 Dec  6 14:18 openshift.local.config
drwxr-xr-x  103 root     root          4096 Dec  6 14:19 openshift.local.pv
drwxr-xr-x    4 root     root          4096 Dec  6 14:18 openshift.local.volumes
```

Not sure the permission bits are right, wondering if they should be `0755` by default to allow the pods running as non-root user to write to the folder mounted via PVC

**Comment by praveenkumar** [comment]
@kameshsampath when I try to `apply` your gist yaml file, I am getting following error.

````
$ oc apply -f https://gist.github.com/kameshsampath/916ef263f755656ace65d5315b3cb83c
error: error converting YAML to JSON: yaml: line 421: mapping values are not allowed in this context
```

Also, permissions look as expected because any pod in the OpenShift is run as a random ID and that ID has required permission to write to these PV's.

**Comment by praveenkumar** [comment]
@kameshsampath  I also tried cake-php mysql persistent example (https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp-mysql-persistent.json) and it works as expected. It also contains persistent volume https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp-mysql-persistent.json#L386 and mount happen https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp-mysql-persistent.json#L400-L403

**Comment by praveenkumar** [comment]
@kameshsampath any update on this?

**Comment by jorgemoralespou** [comment]
@kameshsampath these images are not made to run on OpenShift.

https://hub.docker.com/r/jboss/keycloak/~/dockerfile/

Ask @goldmann as he might know better, but I think that the reason is that the directories in the image are created with jboss user but then when a randomly user is used at execution time it can not access. Most s2i images have a fixPermissions script that is used to solve this problem on the paths that can be used as mounts.

**Comment by goldmann** [comment]
You may want to read this: https://docs.openshift.org/latest/creating_images/guidelines.html especially the "Support Arbitrary User IDs" section. This explains what other changes need to be made.

Generally speaking this bug is not valid bug against minishift nor about the keyckloak image. You've used wrong image, see https://hub.docker.com/r/jboss/keycloak-openshift/ for a correct one.

/cc @stianst

**Comment by praveenkumar** [comment]
I am closing this issue because the issue was with the image.
