### ISSUE TITLE
Does it make sense to switch the default driver implicitly depending on the OS?

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#215]
Currently minishift switches the default driver used, depending on the OS. I am wondering whether this is a good idea. It makes it harder to troubleshoot and support people trying to use minishift.

People report: "'minishift start' did not work" and without additional information of the OS, it is not clear what's going on. It is something which can also then easily be forgotten when trying to re-produce the problem, leading to misunderstandings, testing effectively different code paths.

Is this really helping the user? Also, taking OS X, xhyve might be the native and potentially faster hypervisor, but I still would recommend to use VirtualBox, mainly it allows to monitor the VM with the VirtualBox manager. xhyve lacks capabilities to monitor running VMs and potentially troubleshooting them.

Thoughts?

**Comment by jimmidyson** [comment]
The reason for having os dependent defaults is to try to give the best ux across platforms. Generally, virtualbox kinda sucks. From vagrant experience, virtualbox has always been a PITA. I understand that it might introduce more support issues but for the user, I strongly feel that defaulting to what we consider to be the best platform virt provider is best.

**Comment by LalatenduMohanty** [comment]
+1 for implicitly defaulting to hypervisors for OSs which we think works best for users.

**Comment by jorgemoralespou** [comment]
Have u guys considered having a config settings for minishift. Let's say I'm running on mac, but minishift always decides to start my vms on xhyve, but I want to run them on VirtualBox. If you let the process minishift take the decision, I as a user, want to be able to override it, but by default, and not every time I create the machine.

Also, there should be an implicit log stating which driver/hypervisor is using, as people tend to forget.

**Comment by jimmidyson** [comment]
Can't remember if I added the config view/set subcommand we added to minikube but that does exactly what you're suggesting.

**Comment by hferentschik** [comment]
> Generally, virtualbox kinda sucks.

Why, it is the smallest common denominator across all platforms and imo is is the most stable one (admittedly I have not used Hyper-V a lot). It also has a nice independent UI which allows me to monitor and trouble shoot the VMs. 

> From vagrant experience, virtualbox has always been a PITA.

The problem was not so much VirtualBox but all the other pieces which had to come together to build the final solution

> The reason for having os dependent defaults is to try to give the best ux across platforms.

I actually disagree that the current algorithm is the best. Let's look at this per OS. On OS X we use xhyve. The benefit here is that it is a native hypervisor and it is faster than VirtualBox. Point taken. On the other hand it is less stable and problems are harder to diagnose and fix due to a complete lack of supporting tools. If I had a choice, I'd prefer to start with VirtualBox and then when I need the speed, switch to xhyve. Btw, I would be interested in doing an actual performance test here.

On Windows the situation is imo even worse. There the algorithm falls short. Hyper-V is selected per default. This is very questionable. What if Hyper-V is not even enabled. Hyper-V is per default not enabled. You need to change BIOS settings and enable it in the machine settings. Why do we think that most people who run Windows 10 will enable Hyper-V. If anything and if possible the algorithm would need to check whether Hyper-V is even enabled.

Even worse, a target big group (at least for the CDK) is Windows 7/8, where running Hyper-V is not even possible (at least not for Windows 7). Meaning the current default will always be wrong. Start explaining this to the users.

**Comment by hferentschik** [comment]
> Have u guys considered having a config settings for minishift. 

I think this is already working. Needs to be tested. If not it is not hard to add.

**Comment by hferentschik** [comment]
> for implicitly defaulting to hypervisors for OSs which we think works best for users.

Provided we can get it right. As mentioned above the current selection of Hyper-V based on Windows OS alone falls completely short of doing a good selection.

**Comment by hferentschik** [comment]
> Also, there should be an implicit log stating which driver/hypervisor is using

That's the absolute minimum we should do - https://github.com/minishift/minishift/issues/216. but I think this is not sufficient.

**Comment by thatdocslady** [comment]
I'm going to document the saga that I went through with my initial installation and launch since it's relevant to this issue, I know I'm not the only one who dealt with is but figured it's good to track it here and document if needed.

I use Fedora 25 and I downloaded the linux minishift binary, which should default to kvm/libvirt. Followed the instructions in the install document and got an error about kvm not found. Asked around and discovered that there's additional manual steps to set up kvm (https://github.com/minishift/minishift/blob/master/docs/docker-machine-drivers.md). Ran thru the steps and got a different error.

Then I was told to use virtualbox instead (can't remember exactly why but I didn't argue). So I ran minishift start again with virtualbox as the vm driver, which failed. Then I discovered that there is a lengthy and complicated process to set up virtualbox on fedora - dnf install from the oracle repo (http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo), must be v5x, need to recompile the kernel module/header/something to integrate vbox into the system, add a bunch of paths to the env vars, and finally enable virtualization in the BIOS (!!!). 

Eventually I managed to spin up the minishift instance, but it took me nearly 2 days (net 1 day but spread out coz I had to juggle other tasks between attempts), countless discussions on IRC, and none of the extra steps that were needed were documented. In fact, we specifically say in the README and in the install document that minishift ships with virtualbox and kvm out of the box and no additional steps are necessary.

I understand that there's a big discussion about changing the default behavior, but regardless of what we exactly do about it in the long term, we should at least document the current behavior if we are going to release this project as it is now. Whether we create release notes with temporary workarounds to get the drivers working, or incorporate the info into the actual instructions, we can't expect users to guess what to do. </rant>

**Comment by jorgemoralespou** [comment]
I would probably say that KVM or Virtualbox should be installed and fully
working for minishift to work. Maybe point to the appropriate
documentation, but this will be different for every combination of OS and
hypervisor version, so would be difficult to maintain, so I would not keep
that here. It should be out of scope of minishift to install these or show
the proper way to install them.
I understand the pain you went through but those instructions should belong
in other place. Here you should just note that these should be required and
functional.

**Comment by hferentschik** [comment]
> but this will be different for every combination of OS and hypervisor version, so would be difficult to maintain, so I would not keep that here. It should be out of scope of minishift to install these or show the proper way to install them.

+1 I second that. We need to draw a line somewhere. We cannot document for each and every OS + hypervisor how to get it to work. There is plenty of information out there which does that. If you go down this path where do you start and where do you end?

> Here you should just note that these should be required and functional.

+1

**Comment by budhrg** [comment]
> Eventually I managed to spin up the minishift instance, but it took me nearly 2 days (net 1 day but spread out 

It might happen with actual users too and he/she may not come to irc for help or couldn't even find in the issue etc.

> I understand that there's a big discussion about changing the default behavior, but regardless of what we exactly do about it in the long term, we should at least document the current behavior if we are going to release this project as it is now. Whether we create release notes with temporary workarounds to get the drivers working, or incorporate the info into the actual instructions, we can't expect users to guess what to do.

+1 for instructions to be properly documented. Might be like part of troubleshooting guide.

**Comment by thatdocslady** [comment]
@hferentschik I agree that we shouldn't double-document information that can be found eslewhere and that we need to draw the line somewhere, but at the moment there is nothing in our docs to even indicate that these prerequisites are required. I had to personally ask for help and received these links directly from the developers, so I'm thinking we need to at minimum mention these somewhere in the installation process.

**Comment by jimmidyson** [comment]
Reading https://github.com/minishift/minishift/#prerequisites does give some idea of pre-reqs, but agree that not prescriptive enough or easy enough to follow.

**Comment by Preeticp** [comment]
+1, link to https://github.com/minishift/minishift/blob/master/docs/docker-machine-drivers.md has been provided in the pre-reqs, but yes, the content needs to be more prescriptive. 
However the point of concern would be wrt Virtualbox, since the doc says 'Minishift ships with drivers for VirtualBox and VMware Fusion out of the box', VirtualBox should not have been this painful. 
KVM has not been mentioned in this, so do we add KVM to the list of drivers supported out of box?

**Comment by budhrg** [comment]
> we add KVM to the list of drivers supported out of box?

Only for Linux I believe.

**Comment by thatdocslady** [comment]
@jimmidyson @Preeticp basically we don't explicitely say that these are prerequisites that might require manual steps, we just vaguely mention that "you have these driver options". Nothing about default drivers either. I'm working on improving the install docs now and will submit a PR with proposed changes.

@budhrg even KVM required me to install and configure stuff by following the steps here: https://github.com/minishift/minishift/blob/master/docs/docker-machine-drivers.md so it's not "out of the box". I will adjust the docs to better point to this document.

**Comment by budhrg** [comment]
@hferentschik Look like minikube had `virtualbox` as default driver https://github.com/kubernetes/minikube/blob/master/docs/minikube_start.md

**Comment by praveenkumar** [comment]
@hferentschik I think we are done with all discussion here so closing this issue also.

**Comment by hferentschik** [comment]
+1  I was planning to close this issue as well. I still believe the chosen approach is not optimal, but I think the ship has sailed.
