### ISSUE TITLE
Improve "minishift ip" error when minishift does not exist

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2163]
### General information

  * Minishift version: compiled from latest master
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1.  $ minishft delete -f
  2.  $ minishift ip
  

### Expected
```
$ minishift ip
Error getting IP: Minishift VM does not exist. 
```

### Actual
```
$ minishift ip
Error getting IP: Docker machine "minishift" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
```

**Comment by LalatenduMohanty** [comment]
It seems the error is coming from libmachine. We should change the code similar to `minishift status` to have the custom error message because asking users to run docker-machine i.e. ` Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one` is wrong.

**Comment by gbraad** [comment]
We should catch most (if not all) issues inside the cmd layer and show our
own.

On Thursday, March 22, 2018, Lalatendu Mohanty <notifications@github.com>
wrote:
> It seems the error is coming from libmachine. We should change the code
similar to minishift status to have the custom error message because asking
users to run docker-machine i.e. Use "docker-machine ls" to list machines.
Use "docker-machine create" to add a new one is wrong.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/kSxkGp2ZmGLD11rcqvE-GsbdUhJVO6VmxqnTXLJeNWuEnkcQebfcrTi1sK-EjaoSjyGcogsJbuoTkaZdjgUEQtX1FQ58mjDwf_wiF0hW65854a_Vg75GAonpXzREk827rLwxdTjqk6kvDPHdDjln9rqD8e9KKQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZud_geJI9dhhwtdolcHFt90hiRqbks5tg1OigaJpZM4S2kq_.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by LalatenduMohanty** [comment]
I have the same weird error for `--set-static`

```
$ minishift ip --set-static
Error getting IP: Docker machine "minishift" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
```
