### ISSUE TITLE
Minishift lists v3.9.0 as valid option but doesn't accept it

### ISSUE THREAD

**Issue by MansM** [minishift/minishift#2172]
Minishift lists v3.9.0 as option but doesnt accept it

### General information

  * Minishift version: v1.14.0+1ec5877
  * OS:  macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. minishift config set openshift-version v3.9.0
  2. minishift start
  3. 
  4. 

### Expected
minishift with openshift v3.9.0

### Actual
 minishift start
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.0' is valid ... FAIL
   v3.9.0 is not a valid OpenShift version

### Logs
n/a

**Comment by anjannath** [comment]
The check is correct, `v3.9.0` client tools are not released in the origin repo https://github.com/openshift/origin

Earlier we printed the openshift versions by checking the release tags of origin images on dockerhub. See #2069 which was fixed by #2120, the next release (v1.15.0) which is happening tomorrow will have the fix in it. Cheers :clinking_glasses:

**Comment by gbraad** [comment]
Marking as invalid as without client tools, no installation will be possible.
