### ISSUE TITLE
"minishift" update is failing

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2189]
### General information

  * Minishift version: v1.15.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Compile minishift from source after the commit from https://github.com/minishift/minishift/pull/2078
  2.  Change Makefile to keep minishift version less than v.1.15.0
  3.  run `minishift update`
 
### Actual
```
$ minishift update
A newer version of minishift is available.
Do you want to update from 1.14.0 to 1.15.0 now? [y/N]: y
Update failed: Directory '/Users/lmohanty/code/gocode/bin' binary doesn't have write permission.
Please fix the permission issue and try running the command again.
```

**Comment by gbraad** [comment]
The issue is line:
https://github.com/minishift/minishift/commit/7469ee34f5ee353e41df7ac7a5645b4ae0071af8#diff-d8ba90165ac3a1ed7d918c9deca1dbb9R188

In my case it tries to create:
```
/workspace/bin/minishift/tmp
```

which means it includes the executable name.

It can NOT create the `tmp`, as it assumes `minishift` here is a folder due to the join
