### ISSUE TITLE
Docker mirrors no longer working

### ISSUE THREAD

**Issue by paoloantinori** [minishift/minishift#2195]
### General information

  * Minishift version:  `minishift v1.15.0+e07e789`
  * OS: Linux / macOS / Windows: `Linux`
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox : `kvm`

### Steps to reproduce

  1. `minishift stop; minishift start    --skip-registration   --openshift-version v3.7.2  --registry-mirror http://anything:5000   --show-libmachine-logs   --server-loglevel 8 --alsologtostderr --v 8 2>&1 | tee minishift.log`
  2. `minishift ssh docker info | grep -C 3 -i mirror`
  3. 
  4. 

### Expected
Sample `docker info` output:

```
11:51:51 (/home/pantinor)$ docker info | grep -C 3 -i mirror
  WARNING: You're not using the default seccomp profile
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://localhost:5000/
Live Restore Enabled: false
Registries: docker.io (secure), registry.fedoraproject.org (secure), registry.access.redhat.com (secure), docker.io (secure)

```

### Actual
Entry not present in logs, and clearly not used if you try to pull an image that should hit your local mirror.

### Logs

Notice that despite this section:
```
sudo mkdir -p /var/lib/boot2docker && printf %s "
EXTRA_ARGS='
--label provider=kvm
--insecure-registry 172.30.0.0/16
--registry-mirror http://192.168.1.74:5000

'
```

the config is not seen at runtime

https://gist.github.com/paoloantinori/ea74b82d953d2aeffc882992f6017bad

**Comment by gbraad** [comment]
I always have a registry mirror in use, so I will surely have another look
at this. Nothing in minishift itself changed for this, ... Or it should
fail due to a package or how the docker daemon now works (we did update the
docker version).


-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by paoloantinori** [comment]
Let me add that I have just downgraded to ```
minishift version
minishift v1.14.0+1ec5877
```

and I can confirm you that it works fine on this version, despite `minishift ssh docker info` doesn't logs it usage explicitly.

**Comment by gbraad** [comment]
I noticed you used B2D. Can you try this with `--iso-url centos` instead?

**Comment by paoloantinori** [comment]
> I noticed you used B2D. Can you try this with --iso-url centos instead?
Will do. I need a faster env for the rest of the day, but I will try it later on.

> Why are you using --skip-registration in the start command? This only applies to using CDK or RHEL images.
In past, I had never fully understood issues with minishift failing to start back. That flag somehow seemed to help but I trust your knowledge and I'll remove it if it doesn't make any sense.

**Comment by praveenkumar** [comment]
@paoloantinori I tried below and looks like `docker info` provide me that registry component available.

```
$ ./minishift start --iso-url centos --registry-mirror http://anything:5000 --show-libmachine-logs -v 5
-- minishift version: v1.15.0+e07e789e
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.7.2' is valid ... OK
-- Checking if requested OpenShift version 'v3.7.2' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
[...]
The server is accessible via web console at:
    https://192.168.42.28:8443

You are logged in as:
    User:     developer
    Password: <any value>

To login as administrator:
    oc login -u system:admin

$ ./minishift ssh -- docker info
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
[...]
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Registry Mirrors:
 http://anything:5000/
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Comment by gbraad** [comment]
@paoloantinori Be aware that we are in the process of deprecating B2D. Although this is long-term, we are focussing our efforts more on using the minikube iso. If you want to have a faster deployment experienc,e try this...

**Comment by paoloantinori** [comment]
Hi guys, so I can confirm that it works fine with `centos` based vm, which is **enough for me**, but I wonder if this should be reported to the user somehow, when this specific setting is used with what I assume is still a different default vm.

**Comment by praveenkumar** [comment]
@paoloantinori Can you close this issue now?

**Comment by paoloantinori** [comment]
yeah, well. it depends on how you want to see this. we definitely have a workaround (using centos image). from feature pov is still a regressions, until `boot2docker` will be officially deprecated, so that this report can be ignored.

for the time being, in my understanding, is still a relevant issue.

**Comment by hantsy** [comment]
Also encountered the registry mirror issue. 
Docker officials registry is unstable in China, we have to use a mirror for it.

I have tried to use the following  command to start minishift.

```minishift start  --iso-url centos --registry-mirror https://registry.docker-cn.com``

It outputs:

```
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM ......................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
Pulling image openshift/origin:v3.9.0
error: FAIL
   Error: error pulling Docker image openshift/origin:v3.9.0
   Caused By:
     Error: Error: No such image: openshift/origin:v3.9.0
Error during 'cluster up' execution: Error starting the cluster.
```

The config set in minishift.

```
minishift config view
- registry-mirror      : [https://registry.docker-cn.com]
- vm-driver            : virtualbox
```


I have tried stop and start again to apply the settings, it did not work as expected.

BTW, I am using Windows 10 and the latest minshift.

**Comment by paoloantinori** [comment]
@hantsy that is actually a different issue. IIRC the initial fetching of openshift images, has never used the docker mirror settings. That's true also for the centos and the boot2docker images.

This happens because these operations occurs before the vm is started and openshift process created, passing it mirror settings.

My suggestion would be to track that as a separate enhancement request.

**Comment by gbraad** [comment]
@hantsy This is exactly mostly a DNS issue for China and not the Docker registry. The Chinese registry is usually only a tat faster, so I do not bother. I override the DNS entry or provide a nameserver on startup `m start --network-nameserver [dns]` (<= which could be a caching one)

It is not the issue as presented, and not reproducible (in Beijing/Unicom):
```
$ minishift start --iso-url centos --registry-mirror https://registry.docker-cn.com
-- Starting profile 'minishift'
<snip /
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
Pulling image openshift/origin:v3.9.0
Pulled 1/4 layers, 26% complete
```

**Comment by gbraad** [comment]
@hantsy I am also in China... I know of the struggles. But this is not the same issue as the OP mentioned... and I am unable to reproduce. Have tried this from Beijing, and several other locations (mostly DCs). We, as Minishift, can not accomodate the issues with the Chinese network. However, we have added the option for alternative nameservers and docker registry mirrors. I can say, this works in my local setup... so I suggest to setup a docker-registry locally or on your notebook: https://git.io/vpkm1

**Comment by hantsy** [comment]
@gbraad  Thanks for your help.

**Comment by budhrg** [comment]
Closing this issue now. Feel free to reopen it.
