### ISSUE TITLE
--logging doesn't work with 3.6.1, 3.7.0, 3.7.1 , 3.7.2

### ISSUE THREAD

**Issue by mshahat** [minishift/minishift#2207]
Hi, 

I've been trying for a week to stand up a minishift instance with --logging EFK stack. 

I'm using macOS 10.13.3 (17D47) , both xvhye and virtualbox, minishift both v1.14.0 and v1.15.1

I've tried to use openshift-version 3.7.2, 3.7.1, 3.7.0, 3.6.1 and all have given all sorts of errors while the ansible pod is trying to provision the stack. 

I was only able to get it working with 3.6.0

Is this being tracked ? how can i get it working with OCP 3.7+ 

Thanks,

**Comment by gbraad** [comment]
Is this about Minishift or CDK?

**Comment by mshahat** [comment]
Hi @gbraad , Minishift using Origin it is. 

`minishift start --logging --openshift-version ` 3.6.1, 3.7.0, 3.7.1, 3.7.2 are all not able to provision the logging setup EFK stack.

Thank you,

**Comment by gbraad** [comment]
We have relabelled `--logging` as experimental as we have difficulty supporting it. This is functionality that gets provided from OpenShift, and so far... it is kind of known to us that is often fails.

@LalatenduMohanty what to do about this? I think we need to escalate this... again! And we should consider to discuss with them more closely when it comes to the rewrite.

**Comment by mshahat** [comment]
Thanks. 

Let me tell you my struggle, I'm using minishift to layout initial parts of an architecture. experiencing details with something i can play with on my machine is of value.

I've faced the same challenge with --metrics. 

Thanks for your support, and i am happy spending sometime testing.  

Cheers,

**Comment by gbraad** [comment]
@jorgemoralespou Do we have a solution for the issues with *logging* and *metrics*? 

Ref: #1302 #2110

**Comment by jorgemoralespou** [comment]
Adding @jcantrill as he might know

**Comment by jcantrill** [comment]
oc cluster up is being completely rewritten for 3.10 by @deads2k.  I'm not certain how it will function.  I at one point was successful in deploying logging from 3.6->3.7 using openshift-ansible and had issues starting with 3.9.  I have not had success in 3.9 due to a change it appears in how ansible_connection=local is honored.  Assuming the images are tagged for the openshift-ansible correctly, logging/metrics should work.

As an aside, I spoke with someone from either this team or CDK team and advised them they could possibly take the same approach outside of 'oc cluster up'.  I'm not familiar with minishift so I don't know what options you have.  You should oor

**Comment by gbraad** [comment]
I am concerned about having this part of our current release... as having it now as-is, it is NOT an experimental feature... maybe we should change this.

**Comment by LalatenduMohanty** [comment]
@gbraad  now it shows as `--logging   Install logging (experimental)` so I do not think anyone thinks that this is not experimental.   But from consistency point of view I agree with you. We should fix it.

**Comment by gbraad** [comment]
I created #2234 and PR #2235

**Comment by LalatenduMohanty** [comment]
@mshahat  Do you still need `--logging` to work with versions < 3.7.0?

**Comment by mshahat** [comment]
Hi @LalatenduMohanty , would be great if it works. at the moment, i'm happy if it's a later version. 

Thanks

**Comment by jcantrill** [comment]
@phawzy I would expect you to be able to provision Openshift with logging and metrics using 'oc cluster up' and origin images for versions: 3.7-3.9.  Versions 3.10-3.11 are just broken to be fixed in later releases.  
I've copied my instructions to [1] which work at the time I wrote it. You may need to fiddle with a few things if they have changed and they very slightly between the various versions.  Additionally, there are other inventory files which may also need to be tweaked depending on the failures you see.

Note:  Later releases should resolve some of the complications as we are moving to use operators which will provide a better OOTB experience.

[1] https://gist.github.com/jcantrill/eca85af2057b84642510cc086f1e5b97

**Comment by jcantrill** [comment]
I can't speak to the state of the upstream images.  Everytime I believe 'latest' or 'latest' of a a particular release is usable, we find it is out of sync with actually building the images and then deploying them.  I think you will find that once 4.0 is available and we move to operators the experience should be better.
