### ISSUE TITLE
minishift openshift version list throws a JSON Unmarshalling exception

### ISSUE THREAD

**Issue by eriknelson** [minishift/minishift#2277]
### General information

  * Minishift version: minishift v1.15.1+a5c47dd
  * OS: Fedora 27
  * Hypervisor: KVM

### Steps to reproduce

  1. Run minishift openshift version list

### Expected
A list of available OpenShift versions.

### Actual
The following error is thrown:
```
Error while trying to get list of available Origin versions: *json.UnmarshalTypeError
json: cannot unmarshal object into Go value of type []version.releaseTags
&json.UnmarshalTypeError{Value:"object", Type:(*reflect.rtype)(0xc32600), Offset:1, Struct:"", Field:""}
```

**Comment by anjannath** [comment]
Sorry, we forgot to handle 403 error from github when hitting its rate limit.. you are probably getting it because of that. There's no json to parse..

You can use github api token, set your token in env variable `MINISHIFT_GITHUB_API_TOKEN` `minishift` will make authenticated requests to github, btw, you'll see a clear error msg now.

```
Error while trying to get list of available Origin versions: Hit github rate limit: GET https://api.github.com/repos/openshift/origin/releases: 403 API rate limit exceeded for 103.228.221.82. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 57m6.196481579s
```
 _Minshift v1.16.0_ released by Monday will have it.
