### ISSUE TITLE
Error message showing up non-existing link

### ISSUE THREAD

**Issue by farhaanbukhsh** [minishift/minishift#2287]
### General information

  * Minishift version: Latest Master
  * OS: Linux
  * Hypervisor: KVM - But the error is when there is no driver installed

### Steps to reproduce

I was trying to set up minishift for development and when ran the binary since I was missing the KVM driver it gave me the following error.

```

-- Checking if KVM driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information

```

When I tried visiting the link it was outdated and it gave me a 404, a quick search landed me up on:
``` https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#kvm-driver-install```

### Logs

```
./minishift start
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
```

**Comment by LalatenduMohanty** [comment]
@farhaanbukhsh The issue is we have recently done some restructuring of the docs  in  https://github.com/minishift/minishift/commit/126bdb39e27cf36e207519ecf8f022cf9678a73c and the latest docs in master [1] is not published yet. Hence you are seeing contradiction. Once we release Minishift today, you would start seeing right docs from tomorrow.  

[1] https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-virtualization-environment.adoc

**Comment by gbraad** [comment]
Documentation and the binary release should happen at the same time.
