### ISSUE TITLE
Minishift start: VM cannot connect to external URL with HTTP

### ISSUE THREAD

**Issue by egkelly** [minishift/minishift#2432]
### General information

  * Minishift version: 
  * OS: Linux 
  * Hypervisor: KVM 

### Steps to reproduce

  1. minishift start --show-libmachine-logs -v2 --http-proxy http://<proxy>:<port> --https-proxy https://<proxy>:<port>

### Explanation

When executing minishift start, I cannot start openshift due to lack of vm connectivity. Specifically, the main problem is "Pulling image registry.access.redhat.com/openshift3/ose:v3.9.14... error: FAIL"
I am operating behind a corporate proxy, which I have flagged in the start command. My host machine is unable to ping 8.8.8.8 or google.com, though I have nameserver 8.8.8.8 in /etc/resolv.conf

### Logs

-- minishift version: v1.15.1+f19ac09
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.14' is valid ... SKIP
github.com is not accessible over internet or host is not connected to internet
-- Checking if requested OpenShift version 'v3.9.14' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .....Running pre-create checks...
Creating machine...
(minishift) Downloading /home/myuser/.minishift/cache/boot2docker.iso from file:///home/myuser/.minishift/cache/iso/minishift-rhel7.iso...
...........Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
.......Detecting the provisioner...
Provisioning with minishift...

   Setting hostname ... 
......OK
.....Copying certs to the local machine directory...
....Copying certs to the remote machine...
......Setting Docker configuration on the remote daemon...
...........Checking connection to Docker...
Docker is up and running!
-- Setting proxy information ... ...OK
 OK
-- Registering machine using subscription-manager
   Registration in progress ............................. OK [1m26s]
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'registry.access.redhat.com/openshift3/ose:v3.9.14' . CACHE MISS
   Importing 'registry.access.redhat.com/openshift3/ose-docker-registry:v3.9.14'  CACHE MISS
   Importing 'registry.access.redhat.com/openshift3/ose-haproxy-router:v3.9.14'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.9.14
-- Running 'oc' with: 'cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-pv-dir /var/lib/minishift/openshift.local.pv --host-volumes-dir /var/lib/minishift/openshift.local.volumes --http-proxy http://proxy:80 --https-proxy https://proxy:80 --no-proxy localhost,127.0.0.1,172.30.1.1 --routing-suffix 192.168.42.225.nip.io'
Pulling image registry.access.redhat.com/openshift3/ose:v3.9.14
error: FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.9.14
   Caused By:
     Error: Error: No such image: registry.access.redhat.com/openshift3/ose:v3.9.14
Error during 'cluster up' execution: Error starting the cluster.

**Comment by anjannath** [comment]
This happens because dns resolution is failing from inside the VM, are you
on a corporate VPN?

**Comment by gbraad** [comment]
it seems to be able to register: 

```
-- Registering machine using subscription-manager
Registration in progress ............................. OK [1m26s]
```

but can you verify the DNS settings? maybeyou need to set `--network-nameserver [corporate-dns]` to allow the VM to resolve addresses.

**Comment by egkelly** [comment]
@anjannath I'm on a corporate network, not VPN though.
@gbraad Adding the --network-nameserver didn't seem to make any difference, HTTP connectivity is still failing with the same errors.

**Comment by egkelly** [comment]
Quick update, I am able to resolve both google.com and an internal corporate website, so the DNS is set up correctly. Could this be a certificate issue?

**Comment by gbraad** [comment]
Unlikely. I have seen this issue once, but wasn't able to reproduce.
It felt like it was related to a misconfiguration.

I suspect proxy to be the issue here...

**Comment by egkelly** [comment]
It turns out the issue was actually a certificate problem. I discovered this by running a docker pull hello-world and it failed with a "certificate signed by unknown authority"

**Comment by lin1000** [comment]
I tried to minishift start --network-nameserver 8.8.8.8 , then it works!

**Comment by RoopeshMajeti** [comment]
I tried with the above options, but then faced with the below error :


------------------------------------------------------------------------------------------------
sudo minishift start --vm-driver hyperkit --network-nameserver 8.8.8.8
-- Starting profile 'minishift'
-- Using proxy for the setup
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.27 MiB / 53.27 MiB [=============================================================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 236.22 MiB / 355.00 MiB [==========================================================================================================================>-------------------------------------------------------------]  66.54% 7m50s 355.00 MiB / 355.00 MiB [===========================================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM .................. FAIL E0808 16:24:05.670342   15074 start.go:494] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

------------------------------------------------------------------------------------------------

Since am on Mac OS, systemctl is not available, but rather apachectl. But not sure, how to configure this inside any script.

**Comment by avisiedo** [comment]
For the record, I am using macOS High Sierra, and I was getting similar issues.

Eventually I have fixed that by disabling "stealth mode".

Go to System Preferences > Security & Privacy > Firewall > [Firewall Options] > [  ] Enable stealth mode

And disable stealth mode if it were enabled.

Double check if some firewall (such as LittleSnitch) is enabled, and adapt the rules properly.

**Comment by Anurag-ui** [comment]
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- **Checking if https://github.com is reachable ... FAIL**
-- Checking if requested OpenShift version 'v3.11.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...

**Comment by dreyTee** [comment]
Still can't fix the issue described.
Using minishift on MacOS.
minishift v1.34.3+4b58f89.
--network-nameserver 8.8.8.8 didn't help.
https://github.com/ opens properly in a browser with normal certificate.

**Comment by dreyTee** [comment]
> -- **Checking if https://github.com is reachable ... FAIL**

In my case corporate VPN was a reason for such behaviour.

**Comment by Jaffar-Vali** [comment]
http://minishift.io/index.html is not reachable, can someone confirm if minishift no longer supported?
