### ISSUE TITLE
proper way to copy/move .minishift between machines?

### ISSUE THREAD

**Issue by tomazb** [minishift/minishift#2439]
### General information

  * Minishift version: minishift v1.15.1+f19ac09 CDK v3.4.0-2
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. Rsync .minishift between two Linux machines with the same minishift version installed and minishift not running
  2. minishift start

### Expected
Minishift to start VM

### Actual
minishift start
-- Starting profile 'minishift'
-- Checking if requested OpenShift version 'v3.9.14' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.14' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .... FAIL E0605 14:34:10.596070   30204 start.go:368] Error starting the VM: Error getting the state for host: virError(Code=7, Domain=6, Message='invalid domain pointer in virDomainGetState'). Retrying.
Error starting the VM: Error getting the state for host: virError(Code=7, Domain=6, Message='invalid domain pointer in virDomainGetState')

### Logs

https://gist.github.com/tomazb/72a045c91ad6c4eb5abe2873a1ee6482

**Comment by praveenkumar** [comment]
@tomazb this is not how it going to work, you can't put exact `.minishift` directory from one linux box to another and assume it works. `~/.minishift/machine` contains host hypervisor stuff and which atm not ported between the machines. 

What you can use is configs, cache ..etc. not everything.

**Comment by praveenkumar** [comment]
More info https://github.com/minishift/minishift/issues/1649 and we can close this issue as duplicate.

**Comment by tomazb** [comment]
@praveenkumar  Thank you for your response. I was hoping it would be that easy since I had compatible environments - including the hypervisor stuff.

**Comment by anjannath** [comment]
@tomazb If everything is same (including the user name, because the paths has to match) and you are using kvm, it is possible to migrate to a new host. You just have to recreate the domain in the new host.

1) First dump the domain information `sudo virsh dumpxml <minishift| or_the_profile name> > dom.xml`
2) in the host machine create the domain from the xml file `sudo virsh define dom.xml`
3) `minishift start`

I haven't tried this myself, but give it a try if you can, and let us know.. 

ref: http://ostolc.org/kvm-move-guest-to-another-host.html

**Comment by LalatenduMohanty** [comment]
> More info #1649 and we can close this issue as duplicate.

@praveenkumar It is not a duplicate as @tomazb wants run rsync between two machines or .minishift.

**Comment by gbraad** [comment]
the issue is that libvirt keeps it configuration in `/etc/libvirt` for networking, and config files in `/var/libvirt` AFAIR. Therefore you have to 'export' the VM, and keep the IDs identical. but why do this in the first place?

The idea would be that a VM, especially also Minishift, should be treated as ephemeral or stateless as possible. I would suggest to use image export and scripts to reproduce the state.

**Comment by gbraad** [comment]
If you want to `rsync`, you should sync the actual content of the VM persistent disk. This is mounted on the VM as `/dev/sda`, and this file lives inside the `.minishift/machines` folder. (Note: this means you need to still do an initial setup of the VM).

**Comment by gbraad** [comment]
BUT...

... you should be aware that you NEED to be sure to get the same IP address on either of the instances, as without this, the certificates are invalid and cause the startup to fail. And, at the moment there is no way using KVM to make the IP address static... as the driver relies on DHCP.

**Comment by praveenkumar** [comment]
@minishift/minishift-dev Do you folks still think we should keep this issue open, I don't feel that we can put an effort in this but #1649 is what currently doable.

**Comment by anjannath** [comment]
@praveenkumar I agree, VM s should be treated as ephemeral, we should put out efforts towards #1649
+1 for closing this.
