### ISSUE TITLE
Adding app secrets to xpaas addon

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2556]
Most of secured app templates in xpaas requires a secret, otherwise they fail to deploy. However those secrets are not present in xpaas addon and need to be downloaded/used from other places, for example: https://github.com/jboss-openshift/application-templates/tree/master/secrets.

Question is whether we should add those secrets as part of xpaas addon.

**Comment by LalatenduMohanty** [comment]
@agajdosi  IMO we should add the secrets too. As a project we are not supposed to take everything required from respective upstreams and add them to the add-on. Because the reason for having add-on is to provide an easier way to these sample applications. We rely on upstream to decide what is good for their projects.

**Comment by LalatenduMohanty** [comment]
> Also, we are supporting that addon from the beginning and didn't get any consumer request about same. I just want to make sure if we are putting effort then end consumer should be benefited.

In this case no feedback might not be a good thing as people out side of Jboss group might not have tried this. I will suggest we talk to middleware folks and figure if this is something required for Minishift users.
