### ISSUE TITLE
Start: SSH cmd err, output: exit status 255

### ISSUE THREAD

**Issue by MarcuSacramento** [minishift/minishift#2568]
### General information

  * Minishift version: 1.19.0-windows-amd64 and 1.20.0-windows-amd64
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Execute `minishift delete --force --clear-cache`
  2. clear .minishift directory
  3. Reinstall Virtualbox
  4. Execute `minishift.exe start --vm-driver virtualbox`

Repeat steps with other iso's of centos.
Error in command line not starts the console
After error, not even `minishift ssh` is able to login.

### Expected

Sucess on prompt, and acess the console

### Actual

> -- Starting Minishift VM ................................................................ FAIL E0708 02:20:28.199659   11140 start.go:414] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

### Logs

[Start.log](https://github.com/minishift/minishift/files/2173403/Start.log)
[minishift debug start.log](https://github.com/minishift/minishift/files/2173412/minishift.debug.start.log)
[minishift ssh debug.log](https://github.com/minishift/minishift/files/2173399/minishift.debug.log)

> -- minishift version: v1.20.0+53c500a
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.9.0'
   0 B / 40.81 MiB    0.00%
   40.81 MiB / 40.81 MiB  100.00% 0s
-- Downloading OpenShift v3.9.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.10.0/minishift-centos7.iso'
   0 B / 344.00 MiB    0.00%
   344.00 MiB / 344.00 MiB    100.00%
   -- Starting Minishift VM ....Running pre-create checks...
   Creating machine...
   (minishift) Downloading D:\Developer\home\.minishift\cache\boot2docker.iso from file://D:/Developer/home/.minishift/cache/iso/centos/v1.10.0/minishift-centos7.iso...
   (minishift) Creating VirtualBox VM...
   (minishift) Creating SSH key...
   .......(minishift) Starting the VM...
   (minishift) Check network to re-create if needed...
   (minishift) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
   ..(minishift) Waiting for an IP...
   .............................................. FAIL

The most visible error:

> .(minishift) DBG | Getting to WaitForSSH function...
(minishift) DBG | Using SSH client type: external
(minishift) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i D:\Developer\home\.minishift\machines\minishift\id_rsa -p 57859] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
(minishift) DBG | About to run SSH command:
(minishift) DBG | exit 0
....(minishift) DBG | SSH cmd err, output: exit status 255:
(minishift) DBG | Error getting ssh command 'exit 0' : ssh command error:
(minishift) DBG | command : exit 0
(minishift) DBG | err     : exit status 255
(minishift) DBG | output  :

Also, is not possible use ssh command on cmd for login on Virtual Machine, even port 22 or port designated in the forward port. 

After logged directly on Virtual Box Machine Interface is possible change the sshd_config file port and connect by ssh command, even so, is not possible start minishift because the error persists at both ports.

**Comment by gbraad** [comment]
Make sure you VM has an IP address. you can check this by opening it from the VM console and use `ip a`. It you have, use the `ssh` client you have and connect as `ssh root@$(minishift ip)`. If this fails, you likely have a faulty SSH client. You have tested with openssh-win32 and some others. but not all OpenSSH builds are correct.

You could remove the ssh binary from the search path and force our native solution.

**Comment by MarcuSacramento** [comment]
Thanks for your repply,

Just for documentation: the last update of Windows 10 enabled the ssh feature in my machine. If you have a git client or, in my case, cmder prompt interface, you need to disable some of them.

Example for  windows:

1. Windows key + x
2. Apps and Feature Menu
3. Programs and Feture Options
4. Turn Features On or Off

Disable SSH feature and start a new cmd

**Comment by krumware** [comment]
THANK YOU for this resolution
Windows 10 Pro 1903 - 18922.1000

If your minishift never seems to start and "fails after 60 attempts", try to start again using `minishift start --show-libmachine-logs -v5` to view log messages.
I received a number of different issues, one of these was the ssh status 255. Another was noticing that sometimes an IP was never obtained.
For the IP issue, the command being used by minishift is `echo (( Hyper-V\Get-VM minishift ).networkadapters[0])`, you can run this in powershell to diagnose issues.

I also tried a method mentioned in another thread about id_rsa file permissions, but that did not work for me. Still since it was related to SSH, I tried the uninstall method listed above.
Here is updated information about uninstalling SSH: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

As soon as I uninstalled, I stopped having this issue and things started working. This was incredibly frustrating without any useful error messages, and combined with reading the sparse openshift docs. Minishift began showing the message `SSH binary not found, using native Go implementation`
Thank you thank you thank you @MarcuSacramento.

To the minishift team, if this is related to recent Windows builds/updates, it may be worth considering adding an option flag to force use of the embedded SSH client rather than using it as a fallback.

**Comment by VanJFlorez** [comment]
Also works for me, thanks in advance @MarcuSacramento.

**Comment by peacepenguin** [comment]
I'm running into this problem on latest windows 10 build 1909 on Hyper-v, vm boots but getting ssh errors due to the windows openssh client being used. So this fix worked for me without removing the built in windows ssh client entirely:

You can just adjust your path environmental variable before you launch minishift. use powershell:

get the current path contents:
`echo $env:path`

set a new path variable that excludes the openssh directory: (this example works fine for me, but adjust as needed from your actual path variable) 

`$env:path="C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\username\AppData\Local\Microsoft\WindowsApps"`

now try: 
`ssh.exe`

ssh.exe SHOULD FAIL to run in this powershell session, that's good. Now launch minishift (change your vmswitch1 to your own switch name), now minishift will use its own, working ssh version:

`C:\apps\minishift\minishift.exe start --hyperv-virtual-switch "vmswitch1"`

**Comment by rahulroy1** [comment]
Hi,
Thanks for the above solution for forcing native solution for ssh client.
But for me after that step, it seems to be forever stuck at below:

_(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x816f40] 0x816f10 <nil>  [] 0s} 192.168.1.195 22 <nil> <nil>}
About to run SSH command:
exit 0
......................................................................................._

Any pointers on how this can be fixed? I have already searched and found another step of removing the default minishift-external virtual network switch and added a new one. Then used minishift config set to this new switch. But no luck.

Please advice.

**Comment by vrmsreddy** [comment]
issue is there only if set MINISHIFT_HOME to other than user_home/minishift
1)if  we run **%user_home%/minishift start --vm-driver=virtualbox  --memory 4096 --disk-size 10g --show-libmachine-logs -v10** everything is ok and no issues
2)**if we run it from other than %user_home% giving same ssh 253 error even i tried by upgrading openshift**
