### ISSUE TITLE
EAP tests failing for release job

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#2644]
We enabled the xpass add-on as the root cause of the original failure was fixed. Refer #2582 . However it still fails.  https://ci.centos.org/job/minishift-release/100/consoleFull 

Refer #2645 also

```
08:04:23 --- Failed steps:
08:04:23 
08:04:23   Scenario Outline: User deploys, checks out and deletes several templates from XpaaS imagestream # features/addon-xpaas.feature:20
08:04:23     And service "eap-app" rollout successfully within "1200" seconds # features/addon-xpaas.feature:24
08:04:23       Error: Not all services successfully rolled out:
08:04:23 Not all successfully rolled out:
08:04:23 Service: 'eap-app'
08:04:23 -StdOut: Deployment config "eap-app" waiting on image update
08:04:23 Waiting for latest deployment config spec to be observed by the controller loop...
08:04:23 Waiting for latest deployment config spec to be observed by the controller loop...
08:04:23 Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
08:04:23 Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
08:04:23 Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
08:04:23 Waiting for rollout to finish: 0 of 1 updated replicas are available...
08:04:23 
08:04:23  Service build output logs: Cloning "https://github.com/jboss-developer/jboss-eap-quickstarts" ...
08:04:23 	Commit:	465e5a2e7900cdb744740745f3d65a110d6e9962 (Add generated docs)
08:04:23 	Author:	Tomaz Cerar <tomaz.cerar@gmail.com>
08:04:23 	Date:	Thu Dec 14 01:05:08 2017 +0100
08:04:23 Pulling image "registry.access.redhat.com/jboss-eap-7/eap71-openshift@sha256:d5a066bf46835c12cc794dc6481f41efe082afc40b7900a87ff9f881764d903a" ...
08:04:23 Found pom.xml... attempting to build with 'mvn -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package --batch-mode -Djava.net.preferIPv4Stack=true -Dcom.redhat.xpaas.repo.jbossorg'
08:04:23 Using MAVEN_OPTS '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError'
08:04:23 Using Apache Maven 3.5.0 (Red Hat 3.5.0-4.3)
```

**Comment by LalatenduMohanty** [comment]
@agajdosi @amitkrout Can you take a look.

**Comment by amitkrout** [comment]
I am looking into it

**Comment by amitkrout** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/19851115/43825471-5d6f95de-9ae4-11e8-8290-a33af62a7c7c.png">
Mostly the template eap71-tx-recovery-s2i is failing because readiness probe is failing after updating the deployment config. However sometime all the pod services rollout successfully without updating dc using readiness probe. IMO we are duplicating checks of service rollout ```And service "<service-name>" rollout successfully within "1200" seconds``` of readiness probe in the feature file. If readiness probe is set in the dc to check for port 8080 and http-end-point over HTTP on the pod IP then again service rollout check does not make sense. 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/19851115/43825513-7bd7c730-9ae4-11e8-840d-5dbb5ef25a9c.png">
Some time the ```eap-app-migration``` pod fails due to insufficient memory as not all the resources are released after deleting ```oc delete all —all```. Some time multiple time of ```oc delete all —all``` is required to clean all the resource which is not happening in the feature file. For example 
```
$ oc delete all --all
deploymentconfig "eap-app" deleted
deploymentconfig "eap-app-migration" deleted
buildconfig "eap-app" deleted
imagestream "eap-app" deleted
route "eap-app" deleted
pod "eap-app-migration-1-bdptj" deleted
service "eap-app" deleted
service "eap-app-ping" deleted

$ oc status
In project My Project (myproject) on server https://192.168.64.9:8443

pod/eap-app-migration-1-bdptj runs 172.30.1.1:5000/myproject/eap-app@sha256:98dde1e66521123c9716b6ba26d51512857d07d6f1f7e0ceb56fe573db28785e

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application.

$ oc delete all --all
pod "eap-app-migration-1-bdptj" deleted

$ oc status
In project My Project (myproject) on server https://192.168.64.9:8443

You have no services, deployment configs, or build configs.
Run 'oc new-app' to create an application. 
```

<img width="512" alt="image" src="https://user-images.githubusercontent.com/19851115/43825665-ddae4574-9ae4-11e8-9e6b-ebc73ad6a06c.png">
One more reason for failure is if the previous template deployment fails then there is a high chance that the next template deployment will fail because of the same image stream resources are still used in the same name space. 

Proposed solution :
1. Run all the template in different name space + Increase memory from 4 GB to 6 GB
2. Run all the template in different name space + Use a light weight eap 7.1 template like eap71-basic-s2i instead of eap71-tx-recovery-s2i

**Comment by agajdosi** [comment]
Some cool findings, @amitkrout. For the `oc delete all --all`, can you please report that to OKD? It seems like a bug if that command does not delete all resources.

+1 for keeping the runs in separate projects and delete them after each deployment :+1:, was thinking about that also.

Are you sure it is due to memory?

**Comment by amitkrout** [comment]
> can you please report that to OKD? It seems like a bug if that command does not delete all resources.

right, before creating the issue I want to confirm the same behaviour on local ```oc cluster up``` environment

> Are you sure it is due to memory? 

Its clearly mention in the attached snap shoot. So nothing encourages me to doubt on other resources. Here mostly memory issue is due to resources in use after ```oc delete all —all``` in the same namespace. So i think 4GB memory would be enough to run template in a fresh namespace.

**Comment by amitkrout** [comment]
Using proposed solution 1 but keeping the memory of 4GB

**Comment by LalatenduMohanty** [comment]
> IMO we are duplicating checks of service rollout And service "<service-name>" rollout successfully within "1200" seconds of readiness probe in the feature file. If readiness probe is set in the dc to check for port and http-end-point over HTTP on the pod IP then again service rollout check does not make sense.

Thats not correct. We are creating the readiness probe with `oc set` command and then checking it. 

> Some time the ```eap-app-migration``` pod fails due to insufficient memory as not all the resources are released after deleting ```oc delete all —all```. Some time multiple time of ```oc delete all —all``` is required to clean all the resource which is not happening in the feature file.

This something seems correct. If it is a resource issue we will see similar issues. 

> Run all the template in different name space + Increase memory from 4 GB to 6 GB
> Run all the template in different name space + Use a light weight eap 7.1 template like eap71-basic-s2i instead of eap71-tx-recovery-s2i

sounds good to me.

**Comment by amitkrout** [comment]
> For the oc delete all --all, can you please report that to OKD? It seems like a bug if that command does not delete all resources.

@LalatenduMohanty @agajdosi https://github.com/openshift/origin/issues/20600

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/2680
