### ISSUE TITLE
Support running minishift on travis

### ISSUE THREAD

**Issue by fabiand** [minishift/minishift#2757]
it would be nice if minishift could be run on travis, just like minikube with --driver=none.

**Comment by praveenkumar** [comment]
@fabiand I think we had the same issue before and if you think it through then instead of minishift you can directly run on cluster up on the Travis CI for testing purpose. Is there anything specific you have the need for minishift when you want to use `none` driver.

Another hack way is to use the generic driver like below but you need to make sure root user should be added to its own auth.

```
$ minishift start --vm-driver generic --remote-ipaddress 127.0.0.1 --remote-ssh-user root --remote-ssh-key ~/.ssh/id_rsa
```

**Comment by gbraad** [comment]
Would `m start --vm-driver generic` targeting localhost or a node work for
you?

**Comment by praveenkumar** [comment]
> Still, is going oc clzuster up going to remain?

@fabiand yes minishift still consume oc cluster up internally so for us --driver none means just running `oc cluster up` on the host which right now you are already doing in the Travis side.

**Comment by fabiand** [comment]
oc cluster up now works nicel.y

I'm now checking if I can get minishift to run as well.

(In general it runs, I just need hacks to enable device plugins feature gate, and fix it).

https://github.com/fabiand/traviskube/
