### ISSUE TITLE
Cannot download checksum: received 404 during installation of 1.0.0.beta2

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#282]
```
minishift start
There is a newer version of minishift available. Do you want to
automatically update from v0.9.0 to v1.0.0-beta.2 now? [y/N] y
Updating to version 1.0.0-beta.2
Downloading updated binary checksum to validate updated binary
E0112 15:55:30.198157   83318 update.go:155] Cannot download checksum: received 404
```

**Comment by hferentschik** [comment]
This won't work. Automatic updates are broken and there is no way to fix this in retrospect for _v0.9.0_. In fact due to various other issues automatic updates are disabled in Minishift now. See https://github.com/minishift/minishift#installing-minishift as well as https://github.com/minishift/minishift/issues/246

Best option is to delete the binary and manually download 1.0.0-beta.2.
