### ISSUE TITLE
Che workspace "Java CentOS" fails to start

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2824]
### General information

  * Minishift version: v1.24.0
  * OS: linux (probably all)
  * Hypervisor: kvm (probably all)

Taken from original report on CDK tracker - [CDK-345](https://issues.jboss.org/browse/CDK-345) as the issue is also valid for Minishift and OKD.

### Steps to reproduce

  1. minishift start --memory 5GB 
  2. (optional step:) minishift addon apply anyuid
  3. minishift addon apply che
  4. then go to Che UI
  5. open workspaces tab, select all workspaces
  6. choose and deploy "Java CentOS" stack

### Expected

Workspace should be started after a while.

### Actual

Workspace fails to start.

### Logs

```
pulling image "eclipse/centos_jdk8"
Successfully pulled image "eclipse/centos_jdk8"
Created container
Started container
mkdir -p /tmp/bootstrapper/ /workspace_logs/bootstrapper
mkdir: cannot create directory '/workspace_logs': Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1
Error: Failed to run the workspace: "Bootstrapping of machine dev-machine failed. Cause: mkdir: cannot create directory '/workspace_logs': Permission denied
command terminated with non-zero exit code: Error executing in Docker Container: 1"
```

### Testing

Because of this issue the Java CentOS workspace runs were disabled in integration tests. 
*As part of this issue tests should be enabled again after it is fixed in upstream Che.*

**Comment by LalatenduMohanty** [comment]
@agajdosi Do we known the root cause of the issue?

**Comment by agajdosi** [comment]
@LalatenduMohanty Root cause is probably the same as in https://issues.jboss.org/browse/CDK-305, the fix is probably needed from Che side.

**Comment by LalatenduMohanty** [comment]
Upstream Che issue https://github.com/redhat-developer/rh-che/issues/912

**Comment by amitkrout** [comment]
Workspace stack ```CentOS WildFly Swarm``` also stuck with anyuid.addon enabled. checking the same locally without  enabling anyuid addon. 

Seems stack related to CentOS having the issue

**Comment by ibuziuk** [comment]
@eivantsov maybe you have some ideas? we are currently adding a workaround with adding  user to the 'root' group. But according to the last comments the problem is reproducible regardless of the anyuid configuration. 

[1] https://github.com/eclipse/che-dockerfiles/commit/f330ab36ccc390a50f11f04fe25cea2d787374ee

**Comment by amitkrout** [comment]
Locally no issue found on stack ```CentOS WildFly Swarm``` without enabling anyuid addon.

**Comment by l0rd** [comment]
@ibuziuk @eivantsov I don't know what the root cause is but I figured out last week that the template used by minishift addon hasn't been updated in months. We need to replace it with upstream one. That may be enough to fix this issue.

**Comment by ibuziuk** [comment]
@l0rd it is a good point, but template version does not seem to be related to this stack issue.

**Comment by l0rd** [comment]
I had a look at this problem:

1) workspace creation of `Java CentOS` hangs only if `anyuid` is enabled
2) the image used by this stack is [eclipse/centos_jdk8](https://hub.docker.com/r/eclipse/centos_jdk8/tags/) and it's 5 months old
3) the image doesn't contain the fix for [CDK-305](https://issues.jboss.org/browse/CDK-305) that was pushed 4 months ago: https://github.com/eclipse/che-dockerfiles/commit/f330ab36ccc390a50f11f04fe25cea2d787374ee
4) the image from registry.centos.org that is updated at every commit [registry.centos.org/che-stacks/centos-jdk8](https://registry.centos.org/che-stacks/centos-jdk8) does contain the fix.

I suspect that when  [CDK-305](https://issues.jboss.org/browse/CDK-305) was closed only [rails, c++ and go stacks where tested](https://issues.jboss.org/browse/CDK-305?focusedCommentId=13602786&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13602786). 

I have opened https://github.com/eclipse/che/pull/11966 to fix this problem and https://github.com/minishift/minishift/pull/3011 to update the template.

**Comment by LalatenduMohanty** [comment]
@agajdosi https://github.com/eclipse/che/pull/11966 is fixed now along with https://github.com/minishift/minishift/pull/3011 so ideally it should have been resolved now. We should cross check this again.

**Comment by agajdosi** [comment]
This is no longer reproducible.
