### ISSUE TITLE
Allow specifying another path for `.kube/config`

### ISSUE THREAD

**Issue by chmouel** [minishift/minishift#2829]
I would like to be able to specify a new path for the `.kube/config` when starting a VM.

I have multiple clusters where I connect to and switch via different KUBECONFIG variable, some of them are remote cluster with admin access and i'd like to stay away from them while doing some minishift.

according to [this](https://github.com/minishift/minishift/blob/aa3dd4c8a84b411a470b60963ec7fecdd1622473/pkg/minishift/oc/oc.go#L104) there is no way to define it, it would be nice if that was an option.

**Comment by gbraad** [comment]
I am not very familiar to this code path, but I expect this to be part of `oc` and them honoring a possible alternative `HOME` folder for this. @praveenkumar might be able to answer this...

**Comment by chmouel** [comment]
the `$HOME/.kube/config` which is used to connect fro the desktop

**Comment by praveenkumar** [comment]
> I am not sure how this is used exactly.

Let me explain the flow and tell why we are doing what we have as of now.

- VM is created
- oc binary copied to VM
- oc cluster up <options> to VM
- oc cluster up always append the cluster context and config to $HOME/.kube/config
- We take that and do same on the host (take out the kubeconfig from VM and put to host in the same path)
- If we do differently then all the users are going to complain about it since once you start the oc cluster up it always show to login as admin user use `system:admin` which actually comes from there.

**Comment by praveenkumar** [comment]
@chmouel does the above explanation make sense or you still think we are doing something wrong here?

**Comment by chmouel** [comment]
@praveenkumar okay no worries,
