### ISSUE TITLE
Provide option to fully manage kubeconfig within MINISHIFT_HOME

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#2871]
The idea is to let Minishift write the kubeconfig data somewhere into $MINISHIFT_HOME. To stay backward compatible, one could provide an option to enable this feature, eg

```
$ minishift start --minishift-managed-kubeconfig
```

Name to be discussed. Alternatively, it could be a persistent flag only. Once set Minishift will write the config to a $MINISHIFT_HOME internal location. 

If _minishift-managed-kubeconfig_ is enabled, you can configure your shell via which would in this case also export the right KUBECONFIG

```
$ eval $(minishit oc-env)
export PATH="/home/john/.minishift/cache/oc/v1.9.0:$PATH"
export KUBECONFIG=/home/john/.minishift/kube/config"
# Run this command to configure your shell:
# eval $(minishift oc-env)
```

This feature would help to keep better track of the local kubeconfig. Currently, _~/.kube/config_ quickly gets very messy if one creates many Minishift instances. If one also has config data one does not want to delete, one needs to carfully prune kubeconfig.

**Comment by hferentschik** [comment]
Relates to #2871

**Comment by LalatenduMohanty** [comment]
Aren't we using the `~/.kube` because `oc` recognizes the location too. If we change the default location then how will `oc` get the required files for authentication ?

**Comment by hferentschik** [comment]
> This way.

Once you work with multiple clusters, you start to appreciate the possibility of separating the configurations. 

It also means a Minishift instance is even more contained, aka is under full control of us.

**Comment by jorgemoralespou** [comment]
@hferentschik this will mean that you'll need to execute this `eval $(minishit oc-env)` on every shell you open.

The underlying problem is how minishift manages .kube/config and should be fixed there. https://github.com/openshift/origin/issues/18645

**Comment by hferentschik** [comment]
> this will mean that you'll need to execute this eval $(minishit oc-env) on every shell you open.

Only if I care and only if I want to keep a config per Minishift instance. It is an optional feature and it is up to the user to use it the way she seems fit.

Personally, I don't have an issue with that. It's not that I constantly open and close shells. Also, if you always want to make sure that your shell is using a _oc_ version which aligns with the minishift instance you are talking to, you need to run _oc_env_ anyways. 

Last but not least, you could add something to your bashrc to handle this for you. 

> The underlying problem is how minishift manages .kube/config and should be fixed there.

Do you mean Minishift or OpenShift? The issue you are referring to is in OpenShift.

**Comment by jorgemoralespou** [comment]
@hferentschik 
> Only if I care and only if I want to keep a config per Minishift instance. It is an optional feature and it is up to the user to use it the way she seems fit.
> Personally, I don't have an issue with that. It's not that I constantly open and close shells. Also, if you always want to make sure that your shell is using a oc version which aligns with the minishift instance you are talking to, you need to run oc_env anyways.
> Last but not least, you could add something to your bashrc to handle this for you.

We're losing user experience every day :-( If we think that adding things to bashrc to fix some behavior is ok. Also, seems as this is thought only to make your life easier rather than the tool better :-(

> Do you mean Minishift or OpenShift? The issue you are referring to is in OpenShift.

I meant OpenShift. Why currently the .kube/config a minishift/openshift instance sucks it's because of that buggy behavior and why we need to look into this kind of workarounds.

**Comment by anjannath** [comment]
Since the `KUBECONFIG` env variable can hold multiple kube config files, and the resulting configuration is sum of all the configs, we can just append the minishift config file to it. This would also let the user access the already existing clusters in the other config file.
```
$ eval $(minishit oc-env)
export PATH="/home/minishift/.minishift/cache/oc/v1.9.0:$PATH"
export KUBECONFIG=$KUBECONFIG:/home/minishift/.minishift/kube/config"
```

**Comment by vap0rtranz** [comment]
I'm not familiar with Go but it looks like the error folks are seeing is being thrown by the func CacheSystemAdminEntries in the kubeconfig package:

`// Write to machines/<MACHINE_NAME>_kubeconfig
if err := ioutil.WriteFile(systemEntriesConfigPath, []byte(out), 0644); err != nil {
	return err
}`  

[source](https://github.com/minishift/minishift/blob/master/pkg/minikube/kubeconfig/config.go)

Why should this be fixed in openshift/origin?!  This is a minishift local credentials cache, no?  Which isn't an openshift/origin way to do it.

Also, it looks like there have been follow-ups from closed Issues that are continuing to have errors caused by this cache, like `oc login -u system:admin`.  Example [1](https://github.com/minishift/minishift/issues/2601) [2](https://github.com/minishift/minishift/issues/3023) [3] (https://github.com/minishift/minishift/issues/3084) (1affected phillips)
