### ISSUE TITLE
Add Java s2i image builder into default minishift distribution

### ISSUE THREAD

**Issue by dgolovin** [minishift/minishift#2882]
There is no Java s2i image builder available in minishift by default. That requires additional stems to allow building java applications. Is there a reason for that?

**Comment by dgolovin** [comment]
There seems no OpenJDK addons in minishift/CDK repositories. I am looking into addons folders. Is there one around I can use?

**Comment by praveenkumar** [comment]
>  Is there a reason for that?

@dgolovin At this moment all the image stream and template which are part of minishift upstream are directly coming from `oc cluster up` and any other imagestream/template if a user required they can add it or can create an add-on. Can you tell us which imagestrem/template you are after right now?

Downstream we enable some of the addons like xpaas one as default so that might have more templates.

**Comment by dgolovin** [comment]
I am after any java s2i builder that can be enabled by default or manually, so I can use that when pushing springboot app from vscode to openshif using OpenShift Connector Extension.

**Comment by praveenkumar** [comment]
@dgolovin is this https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/latest/xpaas-streams/openjdk18-image-stream.json what you want or need?

**Comment by dgolovin** [comment]
Yep, that is the one I used to test springboot booster with latest odo master build which includes new supervisord image.

**Comment by praveenkumar** [comment]
@dgolovin ack but that is something we can't add as default (because of default comes from cluster up side) but now you know the image stream location you can manually add it to running cluster.

**Comment by LalatenduMohanty** [comment]
@dgolovin You need to enable the xpass add-on once i.e. `minishift addon enable xpass` and it gets applied everytime after `minishift start`.
