### ISSUE TITLE
"minishift logs" doesn't work

### ISSUE THREAD

**Issue by rhuss** [minishift/minishift#302]
"minishift logs" with 1.0.0-beta-2 always returns a single empty line. 

This worked with "minishift 0.9.0" prefectly, also with setting the log level.

I'm running minishift on OS X with xhyve.

**Comment by budhrg** [comment]
Also reproducible in Linux too.

**Comment by budhrg** [comment]
This looks to be one of side effect of switching over to `oc cluster up` approach. 
`/var/lib/minishift/openshift.out` was absent in the VM which was responsible for storing logs prior switching to `oc cluster up`.

This issue https://github.com/minishift/minishift/issues/169 is being created to track all the logging activites.

For record purpose, origin is coming up with [logging aggregation concept](https://github.com/openshift/origin/blob/c4835cfd5bea54db684cc5f6de72ea0af8bd93b1/docs/cluster_up_down.md#installing-logging-aggregation).

**Comment by budhrg** [comment]
I think we can close this issue as it is already known and been track through another issue. 

@hferentschik  WDYT ?

**Comment by hferentschik** [comment]
> This looks to be one of side effect of switching over to oc cluster up approach.

That's correct, we need a different approach here now. I think we can utilize _oc_ for this.

> This issue #169 is being created to track all the logging activites.

Nope, that is not correct. Issue #169 is about something else. This is about logging within the CLI as well. 'minishift logs' is about displaying the logs of OpenShift. Different thing altogether.

> For record purpose, origin is coming up with logging aggregation concept.

That's about unifying the logging within the CLI which atm uses multiple logging frameworks and formats.

> I think we can close this issue as it is already known and been track through another issue.

-1, this is actually a regression from expected behavior of Minishift.

**Comment by jorgemoralespou** [comment]
@hferentschik FYI
In oc cluster up you can get those logs if you do:
"docker logs origin" as the logs remain in that container.

Hope this helps.

**Comment by budhrg** [comment]
@jorgemoralespou  Cool thanks. This will help :+1:

**Comment by hferentschik** [comment]
Merged via pull request #315
