### ISSUE TITLE
Improve Error Message when GitHub Rate Limiting hits

### ISSUE THREAD

**Issue by ALRubinger** [minishift/minishift#3108]
### General information

  * Minishift version: `minishift v1.29.0+72fa7b2`
  * OS: Linux / macOS / Windows: `Fedora release 29 (Twenty Nine)`
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox: `KVM /usr/local/bin/docker-machine-driver-kvm`

### Steps to reproduce

  1. Start Minishift : `$ minishift start --memory=8GB`
  2. If unauthenticated requests at the time of start have maxed out the rate limiting for GitHub, observe the error message:
```
Hit github rate limit: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.11.0: 403 API rate limit exceeded for 125.16.100.118. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 27m30s]
FAIL
```
I happened to be sitting in a room with a bunch 'o wonderful DevTools engineers who knew how to handle this.  For one, we can disable the check:

`$ minishift config set skip-check-openshift-release true`

I also got to Googlin' and saw in #3090 that there's an environment variable one may set to make an authenticated request:

`MINISHIFT_GITHUB_API_TOKEN`

How about reflecting those options in the error message so users know what to do next?

**Comment by gbraad** [comment]
This issue is very specific to the network where people access github resources.
We rather do not add documentation links as this location has been moved around before and causes people to get 404 or unknown host as failure. Also, adding the skip would NOT resolve the actual issue, as you will be unable to download due to the rate limit when doing so.

The documentation specifies what to do... or do you have other suggestions?

**Comment by ALRubinger** [comment]
I hear you.  Here's another perspective: I consider myself an above average technologist and seasoned RHT engineer.  I blocked on this issue for over a full day because the error message made it appear that the rate limit was exceeded for my IP block.  I wasn't aware that this was a global limit for unauthenticated requests, affecting all users of Minishift.

IMO this is not a problem we should delegate to documentation alone.  It hadn't even occurred to me to look there for this issue.

This is not some edge case.  When the limit is hit, it affects a large number of users.  For what, a check that can be easily WARNED and bypassed?  It's not worth failing startup.  A `start` command should just work, unless there's some critical, unavoidable exceptional case which prevents it.  A "check for latest" shouldn't block that.

My recommendation is to do a few things:

1) Fix up the error message to give the user better feedback.  Link to the documentation, absolutely, even if you move it and need to update the links later.

    https://docs.okd.io/latest/minishift/troubleshooting/troubleshooting-getting-started.html#github-api-rate-limit-exceeded

2) Find another way to implement this check.  Don't rely on GitHub unauthenticated requests.  We are distributing software to the world at scale, and the default behaviour of `start` does not scale by design.

**Comment by amisevsk** [comment]
I just hit this, and cannot create a new minishift VM (after having to delete my old one). The image is still cached from earlier, so failing start because we can't check the image adds somewhat needless frustration.

For my use case, `minishift config set skip-check-openshift-release true` solves the problem.

**Comment by gbraad** [comment]
>  Don't rely on GitHub unauthenticated requests.

Authenticated requests introduce user experience issues. This only affects Minishift and not CDK, so the impact has been classified as low.

However, when cached I can understand the skip is helpful... and is documented as such. We might update the message, @minishift/minishift-dev WDYT, add the full link?

**Comment by gbraad** [comment]
Originally we were supposed to test for a version file from http/formatted
as json from a static resource, hosted on GitHub pages perhaps. Perhaps
revisit this ...

On Sunday, January 13, 2019, Andrew Lee Rubinger <notifications@github.com>
wrote:
> Authenticated requests introduce user experience issues.
>
> That wasn't quite what I meant. The check here is simply to see if the
user has the most up to date version. There are other ways to accomplish
that aside from hitting the GitHub API.
>
> This only affects Minishift and not CDK, so the impact has been
classified as low.
>
> I would encourage the team to revisit that assessment. The upstream is
not less important than the product, especially when we're talking about
developer experience. Because access to OpenShift is difficult, running it
locally is the most reliable way we have to get it in the hands of users.
And Minishift is critical to our strategy there.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/wePV0NP3XZQO16pZwevAdUSQ5GJN7qVUM2hOKmswWQlQSDuX2tWnVHBNzsfNPA2LNuK0JDQqUiCpkTkr5CGUiWHucBTJnNvp-QiqYs_Vr-FFyi3rnGmGwVF5Mftk8vn6OoaAaHsBRtNP-fiUFBSVXGQLfA=s0-d-e1-ft#https://github.com/notifications/beacon/AAAHZhsILvToQ0DYeYhkgomNrbb3KtF_ks5vCjYBgaJpZM4Z0z-J.gif
>

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
@praveenkumar do you remember why we did NOT go for the publication of a JSON resource on github pages?

**Comment by praveenkumar** [comment]
> do you remember why we did NOT go for the publication of a JSON resource on github pages?

@gbraad I didn't get what you mean `publication of JSON resource on github pages` ?

**Comment by gbraad** [comment]
in the initial issue we discussed and proposed to post the up-to-date information of available openshift versions as a static resource on GitHub pages, minishift.io. This would prevent us to have to access the API. (eg. publish the info as a copy on a regular interval).

**Comment by LalatenduMohanty** [comment]
> I would encourage the team to revisit that assessment. The upstream is not less important than the product, especially when we're talking about developer experience. Because access to OpenShift is difficult, running it locally is the most reliable way we have to get it in the hands of users. And Minishift is critical to our strategy there.

I agree with the upstream vs downstream argument here.  The reason we have kept it as it is the error was quite transparent about the issue. AFAIR you just search the internet about the github rate limit and use the solution github recommends i.e. use of `GH_TOKEN` environment variable and it should be able to fix the issue . 



> However, when cached I can understand the skip is helpful... and is documented as such. We might update the message, @minishift/minishift-dev WDYT, add the full link?

Yes, we should add the full link as the documentation is stable now and I do not expect the link to change.

**Comment by praveenkumar** [comment]
> do you remember why we did NOT go for the publication of a JSON resource on github pages?

@gbraad I didn't get what you mean `publication of JSON resource on github pages` ?

**Comment by gbraad** [comment]
We can avoid touching the API, but placing a json fragment on a github
page. this is served as part of a static resource. This would ONLY change
when the path minishift.io/openshift_versions would be modified. This
avoids having issues with the API rate limit.

Does that make sense?

**Comment by ALRubinger** [comment]
Absolutely!
