### ISSUE TITLE
Add documentation on how to build/compile binary in Windows with Cygwin

### ISSUE THREAD

**Issue by pthorson** [minishift/minishift#3136]
Add documentation on how to build/compile binary in Windows with Cygwin

https://github.com/minishift/minishift/issues/1037#issuecomment-309414383_

**Comment by gbraad** [comment]
You can use https://github.com/minishift/minishift/blob/master/appveyor.yml as a base for this

I am personally not very inclined to add this. For a long time this caused me too many headaches and have since moved on to exclusively using a container to build (using the gitlab-runner and `gitlab-ci.yaml` as defintion). It would rather describe to use minishift with `--no-provision` to trigger this build process

**Comment by pthorson** [comment]
Thank you for your response. Perhaps the action is to update the documentation to indicate this as the recommended approach for Windows users. Even if it doesn't provide a detailed explanation, it might at least point them in the correct direction.

**Comment by gbraad** [comment]
@LalatenduMohanty @robin-owen WDYT?

**Comment by pthorson** [comment]
Looks like Make isn't installed by default in the minimal Ubuntu distribution. (Unless I've missed something.) It shows up at https://docs.okd.io/latest/minishift/contributing/developing.html#build-minishift after not having been mentioned in the pre-requisites. 

Adding that install, 

- `choco install make` (with link to Chocately) for Windows
- `sudo apt insall make` for Linuses 
- `brew <whatever>` for the Mac

might be sufficient to get this pointed in the correct direction for Windows and add necessary documentation for the other environments

> You should be able to develop Minishift on Linux, macOS or Windows

**Comment by robin-owen** [comment]
@pthorson  You're right, `make` should be listed as a prerequisite -- I'm not sure why it isn't documented already. :)

Homebrew has a formula for `make`, so it should be as simple as `brew install make` on macOS. Of course, this assumes that Homebrew is already installed by the reader.

For Linux, it's not quite as simple as `sudo apt install make`. We can always document the most commonly installed distributions, though -- focusing on RPM- and `.deb`-based distributions should cover the majority.

@gbraad If you use a container to build the binary on Windows, would you recommend that in general, across all of the applicable build environments (Linux, macOS, Windows)? If possible, I'd like to have only one preferred method of building the binary documented which works (within reason) for *all* platforms.

As it's documented right now, both building a native binary and cross-compiling for the other targets works painlessly for myself using Linux. Unfortunately, I'm not familiar with what limitations or additional steps may be encountered on Windows, so I'm not sure what needs to be documented for that at the moment.

By the way, do you mind if I ask you some questions on IRC next week regarding the container you've been using, @gbraad?

**Comment by gbraad** [comment]
@robin-owen no worries, anytime.

At some point we played with the idea to use containers to optimize the build process. I had done a lot for this in advance, but met some resistance. Now it is not seen as the modus operandi, although I would ALWAYS prefer people to at least use the documentation container to generate the docs on a `no-provision minishift`. For the build process ? it would be great to do so, especially on Windows but not essential ... also, the process is now slightly more complicated due to the system-tray.

**Comment by robin-owen** [comment]
@gbraad Okay, that's good to know. For now, then, it sounds like we recommend using a container to build the binary on Windows, but we should continue using our current documentation for macOS and Linux, correct?

**Comment by robin-owen** [comment]
@pthorson After discussing this with @gbraad and @LalatenduMohanty, we came to the conclusion that there are too many issues with building the binary on Windows to recommend doing so. There are also issues around using a containerized build process on Windows -- as I understand it, these issues are primarily related to building the system tray.

All of these issues make the build process on Windows non-trivial to document. Because of this, we are considering removing the documentation which suggests that Windows is an appropriate build environment, instead focusing on Linux and macOS.

@gbraad and @LalatenduMohanty may have more information/context to share around the discussion that we had as well. :)

**Comment by LalatenduMohanty** [comment]
@pthorson As @robin-owen mentioned we are planing to remove the documentation for Windows as non of us do development on Windows and the CI (Appveyor) some different mechanism. So it is easy for the documentation for Windows stay out of sync. Let us know if you have a different opinion on this.

**Comment by pthorson** [comment]
Closing as addressed by #3159
