### ISSUE TITLE
Minishift not starting on VirtualBox

### ISSUE THREAD

**Issue by abergmeier** [minishift/minishift#3168]
### General information

  * Minishift version: 1.25
  * OS: Windows
  * Hypervisor: VirtualBox

### Steps to reproduce

    ./minishift.exe start --vm-driver=virtualbox --show-libmachine-logs -v5

### Expected
Should install fine.

### Actual
Has errors.
I guess its due to `HOMEDRIVE=g:` on my machine. Question is how to override that for `minishift.exe` only.

### Logs

https://gist.github.com/abergmeier/3fe136e37cec9799a02c1e870e286e1e

**Comment by agajdosi** [comment]
Hi @abergmeier, it is probably due to `HOMEDRIVE=g:` - more can be seen at https://github.com/minishift/minishift/issues/236. If you are not restricted to not use `C:/` then you can make sure you use Minishift binary from `C:/` and set `MINISHIFT_HOME` env variable to ensure Minishift will use certain directory on `C:/...` as its home. If that does not help you can try to export `HOMEDRIVE=c:`.

**Comment by LalatenduMohanty** [comment]
We should add this to the troubleshooting guide. Hence making this a documentation issue.

**Comment by gbraad** [comment]
This is, if not mistaken, already documented. If it is not there we have to verify what happened

**Comment by gbraad** [comment]
https://github.com/minishift/minishift/blob/009893bef6816a1daab59199531feae964c92e38/docs/source/getting-started/installing.adoc?L23

**Comment by gbraad** [comment]
@LalatenduMohanty This is already there in the installation topic. Can we close this?

**Comment by abergmeier** [comment]
If MINISHIFT_HOME is sufficient - IMO it should be named as an alternative in the docs.
