### ISSUE TITLE
Incorrect Virtual Box version check

### ISSUE THREAD

**Issue by skabashnyuk** [minishift/minishift#3180]
### General information

  *  minishift v1.31.0+cfc599c
  *  macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1.  minishift start
 
### Expected
minishift started

### Actual
minishift not started

### Logs
```
[16:47:42]sj:~#: minishift start --skip-startup-checks
-- Starting profile 'minishift'
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    9 GB
   vCPUs :    4
   Disk size: 20 GB
-- Starting Minishift VM ..... FAIL E0221 16:48:16.628848    2084 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.4r128413\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"
```

**Comment by praveenkumar** [comment]
https://github.com/machine-drivers/docker-machine-driver-xhyve/pull/214 we do need to release soon but meanwhile, you can try `brew install docker-machine-driver-xhyve --HEAD`

**Comment by skabashnyuk** [comment]
@praveenkumar  with the HEAD version of driver I have 

```
-- Starting profile 'minishift'
json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string
```

**Comment by praveenkumar** [comment]
> but it's probably not related to this topic

Actually it is because `xhyve` driver structure is changed from `0.3.3` version to HEAD now the `Virtio9p       bool` is `Virtio9p       []string` one :( , I am going to open this issue back and we need to update it to both the places.

- https://github.com/machine-drivers/docker-machine-driver-xhyve/commit/dff9c59d8b9fe8cfcdd180aee12fc700261006e1

**Comment by anjannath** [comment]
We have to cut a release for https://github.com/machine-drivers/docker-machine-driver-xhyve first before we can change the code in minishift, or else it'll break for other people who are using the old version of the driver.

**Comment by HazCod** [comment]
Any estimation? I am unable to use minishift.

**Comment by gbraad** [comment]
None... at the moment the team is having a face-to-face meeting. We will discuss this quickly, but likely we will not act until the beginning of next week for sure.

**Comment by gbraad** [comment]
@praveenkumar how about the `xhyve` driver. Wouldn't the recommendation be to try `hyperkit` ?

**Comment by gbraad** [comment]
Note: this is related to #831. You probably do not want to run both hypervisors on the same host...

**Comment by praveenkumar** [comment]
@HazCod Can you try hyperkit meanwhile so you are not blocked at least. we need to figure out a way to support both version of xhyve driver. 

@anjannath let's bring this up discussion in a meeting and see how we shouldn't break older and newer version of xhyve.

**Comment by skabashnyuk** [comment]
@praveenkumar I believe this issue is up to date. Would you like me to check again?

**Comment by gbraad** [comment]
As long as you do not have some components of VirtualBox left on your
machine (like not having ran the uninstaller, but merely deleted the
Vbox management interface application) this would be OK. The actual
check is in an external library called 'libmachine', which is since
been in maintenance mode. There is an alternative version.... and in
later versions of machine-driver/machine we could resolve this, but I
am not sure if we will take those patches into Minishift.

At least let us know the status.

On Thu, May 16, 2019 at 2:03 PM Sergii Kabashniuk
<notifications@github.com> wrote:
>
> @praveenkumar I believe this issue is up to date. Would you like me to check again?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
