### ISSUE TITLE
`minishift console --request-oauth-token` opens wrong uri for token request

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift#3203]
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Start the minishift
  2. Wait till it is successful
  3. Execute `minishift console --request-oauth-token`

### Expected
It should open the token request url in browser (_https://clusterip:8443/oauth/token/request_)
### Actual
opens the url _https://clusterip:8443/console/oauth/token/request_

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by anjannath** [comment]
When we run `minishift console --url --request-oauth-token` it just prints the url

```bash
[anjan@localhost]~% minishift console --url --request-oauth-token
https://192.168.42.211:8443/console
```

Same is the case for `minishift console --url --machine-readable`
```bash
[anjan@localhost]~% minishift console --url --machine-readable   
https://192.168.42.211:8443/console
```

I think these flags are not supposed to be used together, if a user wants to get the token he's supposed to run `minishift console --request-oauth-token` which will then open the browser with the token request url and will be able to get the token after logging into the cluster. (see screen shot below)
![2019-03-13-155046_1920x1080_scrot](https://user-images.githubusercontent.com/8885742/54273319-afa41100-45ab-11e9-9eb0-a3475bfafffb.png)


(which is broken as of now because of the change in the console url we made to fix https://github.com/minishift/minishift/issues/2892)

I'll be updating the title/description of this issue to reflect the above mentioned issue. /cc @praveenkumar
