### ISSUE TITLE
Update Makefile to fix CircleCI failures

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#3227]
https://github.com/minishift/minishift/commit/3b0d08c97b7ee130ada5ee6b32659c35bee7b569 broke the  `make validate_commits`. We need to fix the `START_COMMIT_MESSAGE_VALIDATION ` to ignore this commit. 

```
# MISC
START_COMMIT_MESSAGE_VALIDATION = 83af4780db01d9a4607925af83297e32b38a1603
```

[1] https://github.com/minishift/minishift/blob/master/Makefile#L66

**Comment by gbraad** [comment]
Or modify the validation check to allow the description to start with any character, even `- `...

**Comment by apupier** [comment]
the regexp is here https://github.com/minishift/minishift/blob/3b0d08c97b7ee130ada5ee6b32659c35bee7b569/Makefile#L296

it is
`^(Issue #[0-9]+ .*|cut v[0-9]+\.[0-9]+\.[0-9]+)$$`

what I don't understand is that I would expect to have the commit message working because there is ".*"

if I try the message on https://regexr.com/ it seems to be fine.
![image](https://user-images.githubusercontent.com/1105127/55402287-65330600-5553-11e9-80af-44dd05c5ffa6.png)

what is the regexp engine in this makefile?

**Comment by apupier** [comment]
it seems to be the go regular expression:
https://github.com/minishift/minishift/blob/ba29431be4dc0697f605f2993a5d1abb1ff2496f/Makefile#L126
https://github.com/vbatts/git-validation/blob/master/rules/messageregexp/rule.go

which means that it should follow this specification https://github.com/google/re2/wiki/Syntax
the "." is marked as "any character" so don't understand why it is not yet working

**Comment by tsedmik** [comment]
@LalatenduMohanty could we please prioritize this issue ... without the fix the PR checks won't be green :-(

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty could we please prioritize this issue ... without the fix the PR checks won't be green :-(

@tsedmik Agree. Will be on it today.

**Comment by LalatenduMohanty** [comment]
@apupier @tsedmik Check https://github.com/minishift/minishift/pull/3242 for the fix.
