### ISSUE TITLE
Error during 'cluster up' execution: Error starting the cluster. ssh command error - v1.33.0

### ISSUE THREAD

**Issue by kujalk** [minishift/minishift#3230]
Installing minishift v1.33.0 and v1.30.0 FAILS with .ssh command error

Error -

 Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.13.0/minishift-centos7.iso'
 346.00 MiB / 346.00 MiB [=================================================================================] 100.00% 0s
-- Starting Minishift VM ................................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ..................... OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .....................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --public-hostname 192.168.99.103 --routing-suffix 192.168.99.103.nip.io --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0'
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0405 04:04:22.443954    2503 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0405 04:04:26.699399    2503 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 92% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.103 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0405 04:04:52.383537    2503 config.go:40] Running "create-master-config"
I0405 04:04:59.721424    2503 config.go:46] Running "create-node-config"
I0405 04:05:02.007720    2503 flags.go:30] Running "create-kubelet-flags"
I0405 04:05:02.611795    2503 run_kubelet.go:49] Running "start-kubelet"
I0405 04:05:02.897007    2503 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0405 04:10:02.902308    2503 run_self_hosted.go:571] API server error: Get https://192.168.99.103:8443/healthz?timeout=32s: dial tcp 192.168.99.103:8443: connect: connection refused ()
Error: timed out waiting for the condition

**Comment by dahooo** [comment]
+1

**Comment by kujalk** [comment]
After some tries, I found that the above error appeared because of lack of physical resources in my system/PC to run the minishift environment. The error output on the screen is completely misleading. One will think its because of lack of any dependency software. Once I tried it worked without any problem and the next try it failed with the same above error. Finally I discovered the problem is only due to lack of resources in my physical machine.

**Comment by priyankamakwana4** [comment]
I am getting same issue. I do not have issues with physical resource. I have been trying since long but ending up getting this error.

Minishift version: v1.34.0+f5db7cb
OS: Windows 10
Hypervisor: Virtual Box

-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Powershell is available ... OK
-- Checking if Hyper-V driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
PS C:\WINDOWS\system32> Remove-Item -Recurse -Force C:\Users\pmakwana\.minishift\
PS C:\WINDOWS\system32> minishift delete -f
PS C:\WINDOWS\system32> minishift config set vm-driver virtualbox
No Minishift instance exists. New 'vm-driver' setting will be applied on next 'minishift start'
PS C:\WINDOWS\system32> minishift start --skip-registration --network-nameserver 8.8.8.8
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.59 MiB / 53.59 MiB [==========================================================================================================================================================================================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.15.0/minishift-centos7.iso'
 355.00 MiB / 355.00 MiB [========================================================================================================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ........................................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ................................ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster .......................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.99.100 --routing-suffix 192.168.99.100.nip.io --base-dir /var/lib/minishift/base
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0725 17:15:42.919928    5316 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
E0725 17:15:44.643860    5316 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulling image openshift/origin-node:v3.11.0
Pulled 5/6 layers, 85% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.100 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
I0725 17:16:20.775520    5316 config.go:40] Running "create-master-config"
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0725 17:16:31.108342    5316 config.go:46] Running "create-node-config"
I0725 17:16:35.237968    5316 flags.go:30] Running "create-kubelet-flags"
I0725 17:16:36.785234    5316 run_kubelet.go:49] Running "start-kubelet"
I0725 17:16:37.288388    5316 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
E0725 17:21:37.300062    5316 run_self_hosted.go:571] API server error: Get https://192.168.99.100:8443/healthz?timeout=32s: dial tcp 192.168.99.100:8443: connect: connection refused ()
Error: timed out waiting for the condition

**Comment by priyankamakwana4** [comment]
@kujalk if you have any suggestions, please help me.

**Comment by dileep-dev** [comment]
Facing same error..

Error - Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.13.0/minishift-centos7.iso' 346.00 MiB / 346.00 MiB [=================================================================================] 100.00% 0s -- Starting Minishift VM ................................. OK -- Checking for IP address ... OK -- Checking for nameservers ... OK -- Checking if external host is reachable from the Minishift VM ... Pinging 8.8.8.8 ... OK -- Checking HTTP connectivity from the VM ... Retrieving http://minishift.io/index.html ... OK -- Checking if persistent storage volume is mounted ... OK -- Checking available disk space ... 1% used OK -- Writing current configuration for static assignment of IP address ... OK Importing 'openshift/origin-control-plane:v3.11.0' . CACHE MISS Importing 'openshift/origin-docker-registry:v3.11.0' . CACHE MISS Importing 'openshift/origin-haproxy-router:v3.11.0' . CACHE MISS -- OpenShift cluster will be configured with ... Version: v3.11.0 -- Pulling the OpenShift Container Image ..................... OK -- Copying oc binary from the OpenShift container image to VM ... OK -- Starting OpenShift cluster .....................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error: command : /var/lib/minishift/bin/oc cluster up --public-hostname 192.168.99.103 --routing-suffix 192.168.99.103.nip.io --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' err     : exit status 1 output  : Getting a Docker client ... Checking if image openshift/origin-control-plane:v3.11.0 is available ... Pulling image openshift/origin-cli:v3.11.0 E0405 04:04:22.443954    2503 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously Image pull complete Pulling image openshift/origin-node:v3.11.0 E0405 04:04:26.699399    2503 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously Pulled 5/6 layers, 92% complete Pulled 6/6 layers, 100% complete Extracting Image pull complete Checking type of volume mount ... Determining server IP ... Using public hostname IP 192.168.99.103 as the host IP Checking if OpenShift is already running ... Checking for supported Docker version (=>1.22) ... Checking if insecured registry is configured properly in Docker ... Checking if required ports are available ... Checking if OpenShift client is configured properly ... Checking if image openshift/origin-control-plane:v3.11.0 is available ... Starting OpenShift using openshift/origin-control-plane:v3.11.0 ... I0405 04:04:52.383537    2503 config.go:40] Running "create-master-config" I0405 04:04:59.721424    2503 config.go:46] Running "create-node-config" I0405 04:05:02.007720    2503 flags.go:30] Running "create-kubelet-flags" I0405 04:05:02.611795    2503 run_kubelet.go:49] Running "start-kubelet" I0405 04:05:02.897007    2503 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ... E0405 04:10:02.902308    2503 run_self_hosted.go:571] API server error: Get https://192.168.99.103:8443/healthz?timeout=32s: dial tcp 192.168.99.103:8443: connect: connection refused () Error: timed out waiting for the condition
--

**Comment by Koulini** [comment]
I'm also facing the same issue,when i tried to install minishift on my mac.
-- Starting OpenShift cluster ...........................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname <ip> --routing-suffix <ip>.nip.io
err     : exit status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E0616 18:53:14.926083    2351 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E0616 18:53:19.174875    2351 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 85% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP <ip>  as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0616 18:53:43.385642    2351 config.go:40] Running "create-master-config"
I0616 18:53:45.745290    2351 config.go:46] Running "create-node-config"
I0616 18:53:46.534604    2351 flags.go:30] Running "create-kubelet-flags"
I0616 18:53:46.893172    2351 run_kubelet.go:49] Running "start-kubelet"
I0616 18:53:47.061936    2351 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0616 18:54:46.075020    2351 interface.go:26] Installing "kube-proxy" ...
I0616 18:54:46.075673    2351 interface.go:26] Installing "kube-dns" ...
I0616 18:54:46.075682    2351 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0616 18:54:46.075686    2351 interface.go:26] Installing "openshift-apiserver" ...
I0616 18:54:46.075721    2351 apply_template.go:81] Installing "openshift-apiserver"
I0616 18:54:46.076420    2351 apply_template.go:81] Installing "kube-dns"
I0616 18:54:46.077351    2351 apply_template.go:81] Installing "kube-proxy"
I0616 18:54:46.077755    2351 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0616 18:54:49.754422    2351 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition

**Comment by lotosotol** [comment]
same here:

```
-- Starting OpenShift cluster ....................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --public-hostname 192.168.99.102 --routing-suffix 192.168.99.102.nip.io --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0'
err     : Process exited with status 1
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.102 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I0123 04:58:35.976642    2743 flags.go:30] Running "create-kubelet-flags"
I0123 04:58:36.430489    2743 run_kubelet.go:49] Running "start-kubelet"
I0123 04:58:36.729216    2743 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I0123 04:58:56.778933    2743 interface.go:26] Installing "kube-proxy" ...
I0123 04:58:56.779922    2743 interface.go:26] Installing "kube-dns" ...
I0123 04:58:56.779933    2743 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I0123 04:58:56.779940    2743 interface.go:26] Installing "openshift-apiserver" ...
I0123 04:58:56.779969    2743 apply_template.go:81] Installing "openshift-apiserver"
I0123 04:58:56.780834    2743 apply_template.go:81] Installing "kube-proxy"
I0123 04:58:56.781646    2743 apply_template.go:81] Installing "kube-dns"
I0123 04:58:56.781755    2743 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I0123 04:59:05.816706    2743 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
```
