### ISSUE TITLE
Document hypervisor requirements: Hyper-V

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#326]
In our current `README.md` we mention that Virtual Extensions (VT-x) is needed for most hypervisors, but mention specifically for Hyper-V this should be disabled.

Microsoft's documentation shows that VT-x is needed: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements and also https://en.wikipedia.org/wiki/Hyper-V#VT-x_handling mentions this. Likely an issue will result when people try to run more than one hypervisor on the same machine, such as VirtualBox or VMware.

We might need to document this better. It might very well be that machine specific issues apply, such as VT-d options, etc.

**Comment by hferentschik** [comment]
I am adding some of my observations we I am trying several options on my Lenovo ThinkPad T450S with Windows 10 Pro with both Hyper-V and VirtualBox installed.

First off, you cannot use libmachine with VirtualBox when Hyper-V is enabled. Using Minishift with VirtualBox while Hyper-V is enabled results in:

    .\minishift.exe start --vm-driver virtualbox
    Starting local OpenShift instance using 'virtualbox' hypervisor...
    E0124 12:10:05.762100    5392 start.go:135] Error starting machine: Error creating. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)". Retrying.
    ...

From a Minishift point of view we are stuck now, since we don't have a fix for issue #305. One could try with docker-machine to test whether '--virtualbox-no-vtx-check' would allow you to continue.

**Comment by gbraad** [comment]
Docker for Windows does not support VirtualBox:, and state in their documentation (IIRC the installer) "Hyper-V is not compatible with Oracle VirtualBox. Therefore, you cannot run the two solutions simultaneously.", related to the exclusive use of the Virtual Extensions  https://docs.docker.com/machine/get-started/

**Comment by hferentschik** [comment]
When turning off Hyper-V, 

    .\minishift.exe start --vm-driver virtualbox

succeeds, regardless of the VT-d BIOS setting.

**Comment by hferentschik** [comment]
I now switched back to Hyper-V, with and without having VT-d enabled. In both cases it worked. Seemed the warning in the docs is not correct and should be removed. At least for now I seem to be able to switch between VirtualBox and Hyper-V by turning on/off the Hyper-V issue and "just" restart.

I am sure though, that I had issues when turning on Hyper-V before. I think it was something along the lines of "not able to enable Hyper-V, because configuration could not be written". I think there I did a restart and also changed BIOS settings. I guess it was the restart which did the trick and the BIOS change was irrelevant.

**Comment by budhrg** [comment]
> I guess it was the restart which did the trick and the BIOS change was irrelevant.

Yes might be. I never got chance to look into the BIOS settings :smile:

**Comment by gbraad** [comment]
Confirmed today that installing Hyper-V without enabling Virtualization Technology will fail. Also, when Second-Level Address Translation is not possible, such as Core2Duo based processors (eg. Q6600), Hyper-V will also fail to install. Compatibility can be verified with PowerShell.

```
PS C:\WINDOWS\system32> SystemInfo

Host Name:                 XXXXXXXXXX
OS Name:                   Microsoft Windows 10 Professional Edition
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
<snip />
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: No
                           Data Execution Prevention Available: Yes
```
_Note: this is a system that doesn't meet requirements_

**Comment by budhrg** [comment]
Related to #265

**Comment by thesteve0** [comment]
It is well know that Hyper-V does not allow any other virtualization tech on the machine. There is a hack so that you can mess with the registry and reboot the machine to switch between HyperV and VirtualBox without uninstalling. 

This is not officially "our issue" but I do think it would be nice to put on top of the windows instructions. Basically tell them to pick a virt technology and stick with it since they are mutually incompatible.

Let me know if you want instructions on the hack.

**Comment by budhrg** [comment]
@thesteve0 

> Let me know if you want instructions on the hack.

Thanks. Happy to know it :smile:

**Comment by gbraad** [comment]
We will have to update the `README.md`, and instead mention (or refer to the Microsoft documentation), that running Hyper-V does not allow the use of other virtualization tools on the same machine.

**Comment by thesteve0** [comment]
I can not find an official statement but you can find plenty of posts talking about it for VMWare or VirtualBox

http://www.lakshmikanth.com/vmware-workstation-and-hyper-v-are-not-compatible/

**Comment by gbraad** [comment]
@thesteve0 yes, the exclusivity is not officially mentioned by them, however tools like `systeminfo` will report issues when another tool is installed. The best we can do is refer to pages like:

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/

or

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements

and mention in our own words that no other virtualization tools should be installed on the machine.

**Comment by budhrg** [comment]
@gbraad 

> and mention in our own words that no other virtualization tools should be installed on the machine.

I think I can work on hyperv fine being Virtualbox installed in my machine. 
I think the information here should be one cannot use both provider simultaneously. In case, if one want to use other provider, then he need to disable hyperv feature.

**Comment by gbraad** [comment]
953c4cac5 removed the text about enabling Virtualization Technology

**Comment by gbraad** [comment]
@hferentschik @thatdocslady I think we can close this. The README has been updated and the documentation will just state that Hyper-V is a possible vm-driver. For requirements, we can refer to Microsoft documentation. WDYT?

**Comment by hferentschik** [comment]
@gbraad 

>  I think we can close this.

+1
