### ISSUE TITLE
Checking if requested OpenShift version 'v3.11.43' is valid ... FAIL

### ISSUE THREAD

**Issue by suulperi** [minishift/minishift#3321]
### General information

  * Minishift version: v1.27.0+5981f996 / CDK v3.7.0-1
  * OS:  macOS
  * Hypervisor:  xhyve 

### Steps to reproduce

  1. Follow official instructions for installing minishift
  2. Run command: minishift start

### Expected
Minishift would be up and running

### Actual
Minishift start fails.

###
I can bypass issue with configuring settings: minishift config set skip-check-openshift-release true

But i don't see this is correct way to solve issue.

**Comment by gbraad** [comment]
It is a way to go around the version check and valid, Pre-flight checks were designed ot be skipped in case of erroneous behaviour or user override. This is because external resources (like internet) should NOT have to fail a startup. We either WARN as default, or allow you to override these.

And the version check is one of the checks that rely on information from a registry, in this case Docker's hub. At times it can fail to check correctly, like an issue with their endpoint, S3 not responding as expected, geo-location (CDN) not returning a valid answer, or due to upload/update of the container images (which makes the tag go out of sync for a short while)

I suggest you to try again and let us know. I have not been able to reproduce this ...

**Comment by titiag01** [comment]
today:29-10-2019:
C:\minishift>minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.43' is valid ... FAIL

I have no idea how to solve this. If i use the previous solution (minishift config set skip-check-openshift-release true) and than again 'minishift start' , i get the same fail.

**Comment by basurohit77** [comment]
if you still face the issue :
check the minishift version:
$ minishift version
minishift v1.16.1+d9a86c9

Now check which openshift version it supports:
$ minishift openshift version list
The following OpenShift versions are available: 
	- v1.4.1
	- v1.5.0
	- v1.5.1
	- v3.10.0
	- v3.10.0-rc.0
	- v3.11.0
	- v3.6.0
	- v3.6.1
	- v3.7.0
	- v3.7.1
	- v3.7.2
	- v3.9.0
Now you can specify/ignore specific version that is not working: (For me 3.9.0 not working, so try diffrent one)
$ minishift start --openshift-version=3.7.2  --vm-driver=virtualbox

If still it not works its because of internet issue or due to the depriciated version of Docker v1 Content
Read: https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.7/html/release_notes_and_known_issues/known_issues

use the command to ignore version check:
$ minishift config set skip-check-openshift-release true
