### ISSUE TITLE
Concurrent runs with different drivers

### ISSUE THREAD

**Issue by marekjelen** [minishift/minishift#369]
When minishift start with one driver, e.g.

```
minishift start
```

that defaults to `xhyve` on macOS and prints

```
Starting local OpenShift cluster using 'xhyve' hypervisor...
```

and it accidentally fails on the `oc cluster up` step , so the VM is provisioned and running, but the OpenShift is not. Another run with different driver, e.g.

```
minishift start --vm-driver=virtualbox
```

prints 

```
Starting local OpenShift cluster using 'virtualbox' hypervisor...
```

and prints exactly the same output and the `oc cluster up` fails as well.

The problem is that the 2nd start does not happen through the `virtualbox` driver as it's printed in the output but does it with the original `xhyve` driver. That's why it fails both drivers and it is not obvious that it failed twice for the `xhyve` driver.

**Comment by hferentschik** [comment]
You are basically running into a variation of issue #179. You cannot switch drivers like this. You need a 'minishift delete' in between. You need to (re-)start a created VM with the appropriate settings (most importantly vm-driver has to match), otherwise you are getting into an inconsistent state. 

This will be addressed if not in the upcoming release, but latest the one after that.
