### ISSUE TITLE
Exporting pull request artifacts to a storage box

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#415]
See https://github.com/minishift/minishift-ci-jobs/issues/1#issuecomment-280229034

**Comment by hferentschik** [comment]
Let's try to summarise what we want:

* Only successful builds passing the tests should deploy their artefacts 
* We want to publish artefacts from the pull request builds as well as from the master build
* The pull request builds should publish under http://artifacts.ci.centos.org/minishift/minishift/pr/<pull request id\>. So the key is the pull request id. Ideally cleanup would be based on whether a pull request gets merged, but we might get away with a rolling deletion as well.
* Every push to master triggers a build as well. This build if successful publishes artefacts as well. (Right now we don't seem to do master builds at all. Maybe we need a different issue for this altogether)
* A master build should publish to http://artifacts.ci.centos.org/minishift/minishift/master/<jenkins-job-id\>
* The build scripts should echo the final artefact URL as part of the build logs, so that one can click straight from the build log to the download
* The documentation needs a new section about CI mentioning CentOS CI (and potentially Travis, AppVeyor, ...) and how CentOS CI builds publish artefacts (master vs pr)
* Ideally the status icon in the README shows the status of the latest maser build, not arbitrary pull request build

@budhrg WDYT? Does this make sense?

**Comment by budhrg** [comment]
@hferentschik All seems fine .

> The documentation needs a new section about CI mentioning CentOS CI (and potentially Travis, AppVeyor, ...) and how CentOS CI builds publish artifacts (master vs pr)

Documented CentOS CI as part of PR https://github.com/minishift/minishift/pull/416/files.  Will create a separate issue to document other CI's as well since I need to gatter info about them.

**Comment by budhrg** [comment]
Created https://github.com/minishift/minishift/issues/435 to track CI for master build and https://github.com/minishift/minishift/issues/426 to document other CI platform being used.

**Comment by hferentschik** [comment]
Merged via pull request #416
