### ISSUE TITLE
Provision an existing VM which has been already created

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#467]
It should be interesting that Minishift could provide an option to provision :  

- An existing VM which has been already created (Virtualbox, ...)
- A VM accessible using SSH

**Comment by LalatenduMohanty** [comment]
@cmoulliard I think it is similar to https://github.com/minishift/minishift/issues/392.

**Comment by cmoulliard** [comment]
The other use case implies that a docker daemon has been deployed and is running within the VM @LalatenduMohanty

**Comment by jorgemoralespou** [comment]
@cmoulliard can you explain me what the value of this could be? I see that this can potentially introduce many problems while I don't see any benefit.

**Comment by cmoulliard** [comment]
Added value could be to provision a VM created using VMWare or any hypervisor and running on another machine which is not local (Google Cloud, Azure, Amazon EC2, Private cloud, ...)

**Comment by jorgemoralespou** [comment]
@cmoulliard but what state should you expect from that VM? Minishift uses Docker from the Boot2Docker (centos/rhel) isos, so, unless those VMs in VMWare or cloud could have the same base iso I think it wouldn't be possible to do it properly.

If VMWare is a target, there should be a vm-driver for VMWare as the solution. If Google Cloud, Azure, AWS is a target, there should be a similar --provider=gce|aws|azure where you can just pass the credentials/serviceaccount and minishift will do the exact same thing using Images available in those clouds.

**Comment by cmoulliard** [comment]
My idea is the following in order to avoid to have something too complex to manage/develop:  

1) Create a VM Linux box according to the Minishift requirements [1]
2) Add a new command to minishift (= provision) in order to pass the SSH parameters (user/password/key) that minishift will use to issue the commands required to provision the machine [2]

[1] : What are the requirements needed by minishift to work with a Linux VM ?
[2] : openshifft-ansible issues ssh / scp ... commands to provision a VM

**Comment by jorgemoralespou** [comment]
@cmoulliard @hferentschik I still think that instead of relying on the user creating that VM, if we want to support clouds, we can have images there, like the ISOs required for minishift, that can be used, so the user just needs to provide the cloud credentials/keys and minishift will do all the bootstrapping, like is currently doing. This will minimize amount of potential issues.

But I agree that would be cool to have:

minishift start --provider=gce and have my minishift running in the cloud.

**Comment by cmoulliard** [comment]
As openshift-ansible as designed scripts/instructions to provision gce, aws, ... we coule reuse what they did. The credentials or additional infos could be passed using a yaml file

```
minishift start --provider=local|gce|aws|azure .... --config.yaml
```

**Comment by hferentschik** [comment]
Hmm, I see this more as a special case of issue #392 and the ability to run Minishift on any Docker daemon. In a first step we need to decouple the VM management from all the other OpenShift operations. This could give us in a first step the ability to provision on any host running a Docker daemon. The next step would then be to also for example provision the machine on AWS or Azure. It is definitely a nice to have,  but it will take some time until we will be able to to that stage.

**Comment by jorgemoralespou** [comment]
@hferentschik +1

But be sure to support issues that arise on running on a random docker daemon. There's many breaking changes in Docker, and Openshift is just supported on RHEL/centos docker versions.

**Comment by hferentschik** [comment]
Sure, tbh I think it will take some time before we cross this bridge.

**Comment by jayunit100** [comment]
We can help test / contrib here if anyone else is leading the charge.

**Comment by hferentschik** [comment]
The problem is that if the VM is provisioned, we don't know how it looks like. ATM, we know which ISOs we support and how they are structured. This is partly used in the code. I fear trying to provision any existing VM, is opening a can of worms. 

> We very much need this for CI/CD of our products.

I guess my question would be why? If you want OpenShift, should the VM not be transparent to you? What custom VMs do you need and why? Maybe a better approach is to describe what you expect from the Minishift VM which it does not provide. We might be able to make changes to our ISOs. 

Another way would be to build your own ISO. Something which is known to work the same way as your B2D and CentOS ISO in terms of expectations around Docker. On top of that you can do whatever you want. 

Maybe this leads to us providing some sort of template of what we expect of an ISO. Something people can clone and adjust to have custom ISOs which do, however, adhere to the same bootstrapping etc. To me this would be a more sounds way than trying to provision any odd VM.

**Comment by jayunit100** [comment]
What we need is to run minishift in high memory instances for CI. Right now ec2 or gce obviously can't run Virtualbox.  Custom ISOs are ok, requiring xhyve or virtualbox is not ok though.

**Comment by hferentschik** [comment]
So in your case, why do you want to use Minishift? You could spin up a VM, install Docker and then use 'oc cluster up' directly. Depending on your use case this might be the easier/cleaner solution. Do you need any Minishift add-ons? If so, even that could be scripted. 

I know Minishift rocks ;-), but to a certain degree it has a different use case, namely creating a single node cluster for local development/experimentation. It provides some nice shortcuts and features, but in the end it all wraps around 'cluster up'.

**Comment by budhrg** [comment]
Still to do.

**Comment by hferentschik** [comment]
TBH, I think this should be resolved as won't fix. At least in its most generic form, aka provisioning any running VM, we are not able to do this.

**Comment by gbraad** [comment]
This is a stretch that we might want to do in future, but there are too many factors involved here... for instance, how the VM was setup, ISO/Install, the network settings, etc, and even the name to be able to control if as lifecycle from Minishift.

For the moment, if this is needed, it is better to use `oc cluster up` directly by targeting the node.
