### ISSUE TITLE
Allow installing openshifit-cli

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#503]
It will be nice if openshift-cli can be checked during minishift start and prompt for the user to install the same.

**Comment by hferentschik** [comment]
If you are talking about _oc_, then it is already installed. In fact it is used to provision the OpenShift cluster. You can add it to your PATH. See also https://github.com/minishift/minishift/blob/master/docs/interacting-with-openshift.md#openshift-client-binary-oc

What's missing is to offer a helper command which prints out the right export syntax based on your OS and shell, similar to _docker-env_. That will be addressed by issue #142. 

If this is what you mean, I guess we can close this issue, since _oc_ in installed on the host and #142 will take of the convenience part. WDYT?

**Comment by hferentschik** [comment]
Closing this issue, since as described above _oc_ gets installed on the host. If you feel we misunderstood the issue, feel free to open it again.
