### ISSUE TITLE
Convert README to asciidoc and remove install/quickstart/docker-daemon info

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#533]
- Convert to Asciidoc
- Extract all content which is better suited for docs site

**Comment by thatdocslady** [comment]
Following discussion on PR #621 it was decided to split the work on the README as follows:

I created a new issue #623  to address copying (not move) the "Installation", "Quickstart", and "Reusing the Docker daemon" sections from the README to new topics and place them in their final destinations as asciidoc files in the appropriate sub-directories. 

This is an interim step on the way to getting our docs published, since we cannot remove the information from the readme yet, but we also need to have a complete doc set to test in the coming days and to publish ASAP.

After the docs are published, this issue will address converting the README to asciidoc and removing the duplicate sections, replacing them with a general high-level getting started section and appropriate links to the documentation.

How does this sound? @LalatenduMohanty @Preeticp

**Comment by LalatenduMohanty** [comment]
@thatdocslady +1. We need to change the original description of this issue as per the new plan.

**Comment by Preeticp** [comment]
Sounds good, +1 @thatdocslady

**Comment by hferentschik** [comment]
Merged via pull request #684
