### ISSUE TITLE
Mark oc client downloaded with the platform it is for

### ISSUE THREAD

**Issue by jorgemoralespou** [minishift/minishift#546]
If I have started a minishift instance in an operating system, and I want to make the cached files available to others, by copying some specific files, like the iso and the oc client binary, it will only be possible to use the oc client in the same platform as it was created.

Example:

1. minishift start in OS-X
2. Tar up the folder ~/.minishift/cache/ (this has the file: ~/.minishift/cache/oc/v1.4.1)
3. Copy the tar to a linux box
4. Untar the file into ~/.minishift/cache/
5. export PATH as documented: export PATH=$PATH:~/.minishift/cache/oc/v1.4.1
6. Execute an "oc version"

At this point you'll get an error, since the oc client in that folder is mac specific and not linux.

There needs to be a way to have clients for different platforms and the platform need to be somehow indicated in the filename or in the filepath, so that the folder can be transportable.

Creating this now, as changing this in the future might be a breaking change.

**Comment by jorgemoralespou** [comment]
Has a dependency with #397

**Comment by praveenkumar** [comment]
@hferentschik we need a milestone for same.

**Comment by hferentschik** [comment]
It seems odd to me to have this as a default. For a normal user it makes no sense to download the binary for another target platform. The only use case I can see for this is the pack&go use case, where I want to zip ~/.minishft up to be used on another OS. I think this should somehow be handled by a dedicated command. 

I guess to take some height for this, we could change the chche directory to contains the OS as well, so that one can have multiple oc versions in the cache.

**Comment by budhrg** [comment]
Added milestone as `1.3.0`.

**Comment by jorgemoralespou** [comment]
@hferentschik yes, the pack&go could be the only use case, but it's a use
case we want, and the solution, as you point out, should be as easy as add
an intermediate directory with the OS Arch there.

**Comment by LalatenduMohanty** [comment]
Resolved via https://github.com/minishift/minishift/pull/1693
