### ISSUE TITLE
CentOS CI test fail due to linkage errors

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#579]
See https://ci.centos.org/job/minishift/41/console

**Comment by gbraad** [comment]
This also happens in local builds now... :-s

**Comment by agajdosi** [comment]
Test failures are caused by my PR #576, I am sorry for that. I have changed `integration: $(BUILD_DIR)/$(GOOS)-$(GOARCH)/minishift$(IS_EXE)` to `$(GOPATH)/src/$(REPOPATH)/out/$(GOOS)-$(GOARCH)/minishift$(IS_EXE)`, which worked fine for me, because I did not realized, that target is already build, so everything went fine. However @hferentschik then faced problem with non existing target, because make did not have target for `$(GOPATH)/src/$(REPOPATH)/out/$(GOOS)-$(GOARCH)/minishift$(IS_EXE)`, it has target only for `./out/$(GOOS)-$(GOARCH)/minishift$(IS_EXE)` which caused error. As result of this behaviour MINISHIFT_BINARY was changed:
`MINISHIFT_BINARY ?= $(GOPATH)/bin/minishift$(IS_EXE)`, which is not correct I think.

Quick fix is:
```
.PHONY: integration
integration: $(BUILD_DIR)/$(GOOS)-$(GOARCH)/minishift$(IS_EXE)
	go test -timeout 3600s $(REPOPATH)/test/integration --tags=integration -v -args --binary $(MINISHIFT_BINARY)
```
however this will build the binary if nothing is in ./out/linux-amd64/minishift even if one wants to test her own binary somewhere else. Only possibility I see there in using if else statement. WDYT?

**Comment by hferentschik** [comment]
> This also happens in local builds now... :-s

See pull request #580

> Actually, some 'errors' that occur in go install will not result in an actual error.

Not sure what you mean

> Only on changing a file, the actual compile follows and possible error is returned. 

But that's what you expect, right. Assuming you have a compiled binary, you don't want to re-compile until a change is made, right?

**Comment by hferentschik** [comment]
Merged via pull request #580

**Comment by hferentschik** [comment]
> Test failures are caused by my PR #576, I am sorry for that. 

The problem was there, regardless of the change to the 'integration' test target. It just became apparent, since it forced a default dev build of the binary, opposed to calling _cross_ target.

**Comment by gbraad** [comment]
> > Actually, some 'errors' that occur in go install will not result in an actual error.

> Not sure what you mean

@hferentschik 
![](http://i.imgur.com/NOLDVgt.png)

**Comment by gbraad** [comment]
Or is the location of the binary different from before? In other words, make will ONLY publish the binary in $GOPATH/bin and not as ./out/[platform]/minishift anymore?

**Comment by agajdosi** [comment]
@gbraad seems like ./out/[platform]/minishift is not anymore.

**Comment by gbraad** [comment]
@agajdosi only with `make cross` I guess. Changed behaviour... :-s

**Comment by hferentschik** [comment]
> seems like ./out/[platform]/minishift is not anymore.

It is, for the release and cross compiled binaries. The dev binary gets built into $GOPATH/bin which is the recommended approach.
