### ISSUE TITLE
Add more explicit mechanism to express dependencies between add-ons

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift#650]
ATM, the order of addon execution is given by their priority. This feature suggest to add explicit dependency specification via addiotnal metadata, for example:

    # Name: eap
    # Description: Imports EAP templates
    # Depends on: cluster-admin

In this case the _eap_ template has an explicit dependency to cluster-admin. 

If implemented, there is an overlap with the priority functionality and one might want to consider to remove/deprecate it.

**Comment by hferentschik** [comment]
I wam wondering whether it would not be enough to have the ability to specify a default priority in the metadata:

    # Name: eap
    # Description: Imports EAP templates
    # Priority: 5

Assuming for example, that one wants to run a custom addon after provided addons, one would just set a priority higher then the default.

**Comment by jorgemoralespou** [comment]
I would say that the dependency mechanism could be useful when you have 2
separate addons (xpaas templates and docker pull xpaas templates). I would
probably want to add the templates if I explicitly pull down the xpaas
images. (Maybe not the best example) But this would avoid introducing a 3rd
addon which would do both things together.

**Comment by hferentschik** [comment]
I am just wondering whether one gains anything by switching to named dependencies. You can pretty much achieve the same thing with priority, especially if we allow to define a default priority as part of the metadata. In fact this is even more generic and we don't have to determine cyclic dependencies, etc.

**Comment by jorgemoralespou** [comment]
I think that a dependency of an addon to another is required more than priority, as now we can install/apply at addon at any time and that addon might require another that is not installed or applied.

e.g: 
Look into the [set of commands in the comment](https://github.com/minishift/minishift/issues/1111#issuecomment-314402483). When converting this into an addon, it requires anyuid, or at least anyuid for that user. I can do anyuid for that user, or require the anyuid addon to be installed.

Not the best option, since anyuid would be done on a per user basis, but think about intalling a springboot, where I rely on the xpaas images to be installed.
