### ISSUE TITLE
Fedora packages github.com/cheggaaa/pb but minishift requires gopkg.in/cheggaaa/pb.v1

### ISSUE THREAD

**Issue by marcindulak** [minishift/minishift#651]
`github.com/cheggaaa/pb` is provided in Fedora as `golang-github-cheggaaa-pb-devel`, but minishift requires `gopkg.in/cheggaaa/pb.v1`

```
go test -compiler gc -ldflags '' github.com/minishift/minishift/cmd/minishift/cmd
../../BUILDROOT/golang-github-minishift-minishift-1.0.0-0.1.gite05dbec.fc25.x86_64/usr/share/gocode/src/github.com/minishift/minishift/pkg/minikube/cluster/cluster.go:42:2: cannot find package "gopkg.in/cheggaaa/pb.v1" in any of:
	/usr/lib/golang/src/gopkg.in/cheggaaa/pb.v1 (from $GOROOT)
	/root/rpmbuild/BUILDROOT/golang-github-minishift-minishift-1.0.0-0.1.gite05dbec.fc25.x86_64/usr/share/gocode/src/gopkg.in/cheggaaa/pb.v1 (from $GOPATH)
	/usr/share/gocode/src/gopkg.in/cheggaaa/pb.v1
```

See https://github.com/marcindulak/minishift-rpm-centos7/issues/5 and https://bugzilla.redhat.com/show_bug.cgi?id=1429455

**Comment by hferentschik** [comment]
I am not quite sure what you are asking here. Compile time dependencies for the project are managed by Glide. What is the problem?

Are you saying you are following the workspace setup instructions - https://minishift.io/docs/developing.html#prerequisites - and the build is not working? Not quite sure how this is happening, since Glide will install the vendored libraries in the right version.

**Comment by hferentschik** [comment]
BTW, for all I know the build works fine on Fedora. We have several team members working on Fedora (at least partly).

**Comment by marcindulak** [comment]
The problem is when building minishift from source using the RPM dependencies provided by Fedora.

Fedora provides `github.com/cheggaaa/pb` as RPM and not `gopkg.in/cheggaaa/pb.v1`.

I'm trying to clarify what is the solution to this problem on https://github.com/marcindulak/minishift-rpm-centos7/issues/5

**Comment by LalatenduMohanty** [comment]
@hferentschik The issue comes when @marcindulak is trying to create a RPM  of Minishift for CentOS PaaS SIG.

**Comment by hferentschik** [comment]
Are you saying you are trying to build the project bypassing the Makefile? Effectively building in a custom way. That makes no sense imo. Why can we not just package the Minishift binary into an RPM. AFAIR that was the plan.

**Comment by marcindulak** [comment]
In https://github.com/minishift/minishift/blob/a0a53180478ec02b3b4811560f2fc0168c298298/glide.yaml I see the following comment:
```
# The following repositories need to be specified explicitly, since the versions referenced by the openshift/origin dependency
# refer to forks of these projects within the openshift organizaton
# This needs to be manually updated after upgrading the openshift/origin dependnecy
```
So it looks that we need minishift packaged similarly to http://pkgs.fedoraproject.org/cgit/rpms/docker.git/tree/docker.spec?

**Comment by gbraad** [comment]
The deliverable from the build process is a static compiled binary, so I believe we should build using the `Makefile`, else we would bypass our dependency management and jeopardize al tests as done in CentOS CI, etc.

**Comment by hferentschik** [comment]
> The deliverable from the build process is a static compiled binary, so I believe we should build using the Makefile, else we would bypass our dependency management and jeopardize al tests as done in CentOS CI, etc.

+1 and there is more to it, in our Makefile we are compiling in variables into the code and we generate code as well (gp-bindata). So unless you are using the Makefile I don't see how you actually will be able to build a proper/blessed version of Minishift. 

And to be honest, I don't see the point either. Whom do we help with "rpmifying" go libraries. This is really against how are things done in Go. Are we expecting that Go developers use Go dependencies bundled as rpm? Any sane developer would refrain from that, since it would tie the build to Fedora. To me this makes no sense whatsoever and falls into the same category as using rpms to consume gems.

> This might be something for the future... but at the moment, we are not ready for this.

Not for me. I don't see why one needs to reproduce a build when so much effort is put into creating reproducible builds using the Makefile.

**Comment by hferentschik** [comment]
I propose we close this issue, since I cannot see what action we should take here atm.

**Comment by ingvagabund** [comment]
@marcindulak you can use the Makefile as long as it does not pulls dependency from the Internet. With proper patches the Makefile can be altered so it builds the minishift from fedora deps with debug info on various architectures. If you want to continue with the packaging, please, open a review request in Fedora and let me know. I will see what steps are needed to complete your task.

**Comment by marcindulak** [comment]
@ingvagabund  - thanks for your offer . The current state of the minishift spec file is here https://github.com/LalatenduMohanty/minishift-rpm-centos7/commit/dbe0de1c11c87d47142b03101edd34ae9d183b51 , with some comments/suggestions at the bottom. You may comment there whether we are going in the right direction.

I'll close the current issue - the solution has been suggested https://github.com/marcindulak/minishift-rpm-centos7/issues/5#issuecomment-299123070
