### ISSUE TITLE
Provide --skip-registration and --skip-unregistration flag for subscription based iso's

### ISSUE THREAD

**Issue by kameshsampath** [minishift/minishift#688]
Its observed that the RHN register and unregister is done every time the minishift is started/stopped. It will be nice only to do it when we delete and start the cluster.  Something similar to the options we have with vagrant registration.

**Comment by praveenkumar** [comment]
@kameshsampath In case of vagrant also we had same user experience because what if a user stop VM  without performing un-register and then delete it. In this case he then need to go web console to manually unregister his VM.

**Comment by LalatenduMohanty** [comment]
One could argue that we need to provide a --skip-unregistration option to user if user chooses not to unregister  and hence --skip-registration when doing a start. But the issue has more implications as minishift stop  --skip-unregister -> then minishift start  --skip-register will not work as intended. Because the rootfs is mounted on live-rw and the subscription-manager will loose all information after minishift stop.

**Comment by hferentschik** [comment]
This is really a CDK issue. I created https://issues.jboss.org/browse/CDK-112. Let's have the discussion there.

**Comment by hferentschik** [comment]
Actually, CDK-112 is a duplicate of the already existing https://issues.jboss.org/browse/CDK-102

**Comment by LalatenduMohanty** [comment]
@hferentschik I would suggest to keep this open as we need an upstream issue for the PR (which anyway would need an upstream issue)

**Comment by praveenkumar** [comment]
Right now we are forcefully imposing to do the subscription register for RHEL iso and don't provide a mechanism to skip it. This might be helpful for a user who already have setup ready and want to do now try offline then they can use these --skip parameters.

**Comment by hferentschik** [comment]
Merged via pull request #982
