### ISSUE TITLE
Print out all user information after stop/start

### ISSUE THREAD

**Issue by dustymabe** [minishift/minishift#694]
using `registry.access.redhat.com/openshift3/ose:v3.4.1.12`

when I start minishift the first time I see:

```
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.149:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```

After a stop/start I don't quite get as much information:

```
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.149:8443

   To login as administrator:
       oc login -u system:admin
```

would be nice to get the "you are logged in as" information of the 2nd run as well.

**Comment by LalatenduMohanty** [comment]
@dustymabe this is something we inherit from `oc cluster up`. This need to be fixed in `oc cluster up`.

**Comment by LalatenduMohanty** [comment]
This is also getting changed in cluster up now https://github.com/openshift/origin/pull/13636#issuecomment-291861652

**Comment by jorgemoralespou** [comment]
@LalatenduMohanty still the user will not be logged in the second attempt.
This is the "oc cluster behavior" and might require a "use-context
minishift" after the cluster is started and if that happens, it might be
optional to show a "You're logged in as ...." as @dustymabe suggests
although not the credentials.

**Comment by praveenkumar** [comment]
From minishift side I don't think we have anything to do so closing this. We will reopen if you think we need changes from minishift side here.

**Comment by dustymabe** [comment]
does the upstream issue https://github.com/openshift/origin/pull/13636 fix this? If not then i would prefer to leave this open and have it track a another issue upstream that will solve the problem.

**Comment by jorgemoralespou** [comment]
Here is my view.
Second boot of oc-cluster does not re login the user, hence they remove the output in the startup log. If minishift want to log in the user as part of the "start" process, I guess it could show information about the logged in user.

Minishift could have some problems when using login to log the user in, if you're naming the context in .kube/config, mainly because oc login will not use the named context, and rather create a new one, which could mix things up.

That's one of the reasons I looked into oc-cluster login, so I could reused the named context, as otherwise you can get sometimes that the user is not properly authenticated. This, will even get more complex when using multiple profiles, as you can be a different user in every profile, and they might have same or different IPs, depending on how you guys implement it, so you can be developer on one profile and tester on a different profile, and "oc login" will not know about these profile things. You can potentially have different SSL cert for every profile, as these get autogenerated on "oc cluster up", and they could be identified to the same cluster if they eventually share the same IP.

I'd be happy to have a chat to discuss this complexity.

**Comment by dustymabe** [comment]
@jorgemoralespou - thanks for the explanation. 

I think the one thing I'm trying to overcome is people having to look up what the default username/passwords are for minishift users. I don't necessarily think we need to re-login the user on a second start, but maybe we can actually print out an additional message that tells them:

- what user/password combinations exist with minishift
- if they are currently logged in to the minishift instance that was just brought up and as what user they are already logged in as. 

My main reason for the first bullet point is this user story:

*As a new user I learn about minishift at a conference. During the talk I download minishift and start it on my laptop. I start an example application and then the talk ends and I have to `minishift stop` and go to another talk. 3 weeks later I `minishift start` again (to bring up my existing minishift cluster) and want to log in to the web console. The web console asks me for a username and password. I don't know what username and password to use.*

**Comment by jorgemoralespou** [comment]
@dustymabe I think usually that's what documentation is for.
Minishift just creates one user (developer) and any password works, I don't think learning that justifies the work here.
On the other hand, if minishift used htpasswd auth it created more users, I would understand this requirement.
In any case, not my call. I'm not a minishift developer, just another user.

**Comment by dustymabe** [comment]
> Minishift just creates one user (developer) and any password works

then how hard would it be to just print that out on startup?

Nothing has to be done here if we decide not to. I'm just trying to make the user experience better.
