### ISSUE TITLE
Error running provisioning: something went wrong running an SSH command

### ISSUE THREAD

**Issue by burrsutter** [minishift/minishift#695]
C:\Users\burr\minishift_beta3>minishift version
    Minishift version: 1.0.0-beta.5
    CDK Version: 3.0.0-beta.3

    C:\Users\burr\minishift_beta3>minishift start
    Starting local OpenShift cluster using 'virtualbox' hypervisor...
    E0406 08:28:53.356425    6152 start.go:162] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: something went wrong running an SSH command
    command : sudo hostname minishift && echo "minishift" | sudo tee /etc/hostname
    err     : The handle is invalid.
    output  : . Retrying.
    E0406 08:28:57.393092    6152 start.go:162] Error starting the VM: Error configuring authorization on host: something went wrong running an SSH command
    command : sudo hostname minishift && echo "minishift" | sudo tee /etc/hostname
    err     : The handle is invalid.
    output  : . Retrying.

**Comment by budhrg** [comment]
Hi @burrsutter ,

Bit of incomplete information here. 

What is `minishift config view` result? 

> C:\Users\burr\minishift_beta3>minishift start
Starting local OpenShift cluster using 'virtualbox' hypervisor...

Have you set the vm-driver to virtualbox before running start command?

I doubt you actually hit by this issue https://issues.jboss.org/browse/CDK-70.

@burrsutter , this happens when you don't have `ssh.exe` binary set in your _PATH_. 

We have observed that installing [OpenSSH for Windows](https://sourceforge.net/projects/sshwindows/) resolve above issue. 

Please have a look and let us know.

**Comment by praveenkumar** [comment]
@burrsutter still you are facing same issue or should we close this issue?

**Comment by brandonforster** [comment]
I came across this same issue trying to install OpenShift on a Windows 7 machine. A Google search brought me to this issue, and I can confirm that installing OpenSSH and restarting my command prompt fixed the issue.

I hope you find this report useful.

**Comment by LalatenduMohanty** [comment]
With recent change in Minishift code we do not have a dependency on SSHClient i.e. #1009. Hence closing this issue.
