### ISSUE TITLE
minishift on windows7 and virtualbox failed to start while not working on C:\

### ISSUE THREAD

**Issue by ikke-t** [minishift/minishift#833]
Hi,

several issues here. Customer tried to install minishift on windows 7 using Virtualbox. The customer had no rights to install stuff on C. Also home is set on network drive, so it is not viable option for minishift. Also Virtualbox was too old.

1. we updated VirtualBox (Had to ask admin for creds)
2. Minishift fails to find .minishift dir, it looks it from /.minishift
3. set variables HOMEPATH=E:\home USERPROFILE=E:\home (HOMEDRIVE doesn't seem to be used)

this forced the minishift and virtualbox to use E:\home as path for .minishift. Fine, got further.

Next thing was the Virtualbox somehow failed to read the disk images. The error gets detailed in the log file, similar to this. Unfortunately the succeeded run overwrote the failure log, but the line is like this but with error:

> 1d94.c90: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox

 
It's found from the VM’s log file under minishift directory VBoxHardening.log

At this step, it seems error might be due Virtualbox got updated. Who knows. Windows had to be rebooted at this point, which resolves the issue. Weird, huh ?!?!?

Anyway, after this it works. So two env variables and reboot.

BR, ikke

**Comment by gbraad** [comment]
Hi, thanks for the report. As mentioned on IRC, you used minishift in a domain-policy controlled environment (by means of Active Directory). This way, an admin is able to restrict what a user is allowed to do, such as installations, environment variables, etc. In an environment where people develop for Java on Windows, this is not uncommon, as usually all you need is Eclipse or NetBeans (or whatever editor) extracted from a zip-archive and `javac` and a command line.  In short, this is a situation I predicted, but haven't been able to test yet. I'll close this issue was a record in favor of creating an actual issue. This would probably be in the form of troubleshooting/documentation first.

/cc: @hferentschik @LalatenduMohanty @thatdocslady
