### ISSUE TITLE
Update doc generation for different user id

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#944]
As per [Building Minishift documentation](https://docs.openshift.org/latest/minishift/developing/writing-docs.html#section-building-minishift-docs), to build container for doc with different user id, one need to use `make build_docs_container IMAGE_UID=$(id -u)` which seems to be not helping as during `make gen_docs` it is using UID other than user's id.

```
$ make build_docs_container IMAGE_UID=$(id -u)
cd docs && docker build --build-arg uid=1001 -t minishift/docs .
Sending build context to Docker daemon 3.966 MB
Step 1/21 : FROM ruby:2.4
 ---> f5cfccf11179
...
 ---> Using cache
 ---> 49fa21be8578
Successfully built 49fa21be8578
```

### Generate docs
```
$ make gen_docs
cd docs && docker build --build-arg uid=1000 -t minishift/docs .
Sending build context to Docker daemon 3.966 MB
Step 1/21 : FROM ruby:2.4
 ---> f5cfccf11179
....
Step 15/21 : ADD Gemfile.lock .
 ---> Using cache
 ---> e3ac610971b2
Step 16/21 : RUN /bin/bash -l -c "bundle install;"
 ---> Running in 3301c27e903a

Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/.
...
```

**Comment by hferentschik** [comment]
I think the problem here is that the built uses the caches layers of the image. You are not making any changes to the Dockerfile, so Docker re-uses the old layers. So what's missing here is the ability to remove the image with a dedicated target or a way to optionally set the _--no-cache_ option as part of _build_docs_container_. 

The IMAGE_UID parameters is really only relevant for the _build_docs_container_ target.

**Comment by hferentschik** [comment]
I think we should build the image without any pre-assigned UID. This way the same image can be used for everyone. It will also allow changing the Makefile from building the image to pulling a pre-built image from Docker Hub.

To make this happen, we need to handle the volume permissions as part of the cmd/entrypoint of the image. When the container starts we take the UID of the user on the host, so that we can create a user within the image which matches this UID. Once the user is created, one can switch to this user to execute the various build targets. _gosu_ can, for example, be used for that - https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift/pull/1641
