### ISSUE TITLE
Introduce '--oc-url' option in start command to use cached 'oc' binary

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#963]
It would be great to have start option `--oc-url` so that one can use the cached version `oc` binary. The purpose is similar to `--iso-url` which is used to specify cached ISO during start command.

**Comment by hferentschik** [comment]
> It would be great to have start option --oc-url so that one can use the cached version oc binary

The cached version is used implicitly, what do you gain here? If the _oc_ needed is cached, it will used this cached version. 

I guess you want to point out another _oc_ binary somewhere on the file system. I find this potentially dangerous, since this will potentially bypass version verification we have in place. 

Could you explain a bit more what you are after here?

**Comment by LalatenduMohanty** [comment]
@budhrg I am not convinced that it would add a lot of value. Because Minishift has dependency on `oc` binary version e.g. if you use `oc` binary of Origin version 1.4.1 `$ minishift openshift registry` will not work. You can get older version of OpenShift with newer `oc` binary but the reverse is not true.

**Comment by praveenkumar** [comment]
-1 as @hferentschik said we are not only depend on the binary but also the version which should be known to minishift start process to cache it properly and do required validations.

**Comment by budhrg** [comment]
Anyway, it looks like it is adding more potential risks than benefits. Closing it now.
